/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The AnalyticsBody model module.
 * @module model/AnalyticsBody
 * @version 1.0.1
 */
export default class AnalyticsBody {
  /**
   * Constructs a new <code>AnalyticsBody</code>.
   * @alias module:model/AnalyticsBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AnalyticsBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AnalyticsBody} obj Optional instance to populate.
   * @return {module:model/AnalyticsBody} The populated <code>AnalyticsBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AnalyticsBody();
      if (data.hasOwnProperty('count'))
        obj.count = ApiClient.convertToType(data['count'], 'Number');
    }
    return obj;
  }
}

/**
 * The number of rows to return
 * @member {Number} count
 */
AnalyticsBody.prototype.count = undefined;

