/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The AnswerRatingsBody model module.
 * @module model/AnswerRatingsBody
 * @version 1.0.1
 */
export default class AnswerRatingsBody {
  /**
   * Constructs a new <code>AnswerRatingsBody</code>.
   * @alias module:model/AnswerRatingsBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AnswerRatingsBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AnswerRatingsBody} obj Optional instance to populate.
   * @return {module:model/AnswerRatingsBody} The populated <code>AnswerRatingsBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AnswerRatingsBody();
      if (data.hasOwnProperty('answerId'))
        obj.answerId = ApiClient.convertToType(data['answerId'], 'Number');
      if (data.hasOwnProperty('number'))
        obj._number = ApiClient.convertToType(data['number'], 'Number');
    }
    return obj;
  }
}

/**
 * The answer id
 * @member {Number} answerId
 */
AnswerRatingsBody.prototype.answerId = undefined;

/**
 * The number of previous user ratings to average. Leave blank to average all ratings.
 * @member {Number} _number
 */
AnswerRatingsBody.prototype._number = undefined;

