/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CategorizeBody model module.
 * @module model/CategorizeBody
 * @version 1.0.1
 */
export default class CategorizeBody {
  /**
   * Constructs a new <code>CategorizeBody</code>.
   * @alias module:model/CategorizeBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CategorizeBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CategorizeBody} obj Optional instance to populate.
   * @return {module:model/CategorizeBody} The populated <code>CategorizeBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CategorizeBody();
      if (data.hasOwnProperty('question'))
        obj.question = ApiClient.convertToType(data['question'], 'String');
    }
    return obj;
  }
}

/**
 * The text to categorize
 * @member {String} question
 * @default ''
 */
CategorizeBody.prototype.question = '';

