/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ChatcompletionsMessages from './ChatcompletionsMessages';
import ChatcompletionsTools from './ChatcompletionsTools';

/**
 * The ChatCompletionsBody model module.
 * @module model/ChatCompletionsBody
 * @version 1.0.1
 */
export default class ChatCompletionsBody {
  /**
   * Constructs a new <code>ChatCompletionsBody</code>.
   * @alias module:model/ChatCompletionsBody
   * @class
   * @param model {String} The mAIstro agent to call
   */
  constructor(model) {
    this.model = model;
  }

  /**
   * Constructs a <code>ChatCompletionsBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChatCompletionsBody} obj Optional instance to populate.
   * @return {module:model/ChatCompletionsBody} The populated <code>ChatCompletionsBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ChatCompletionsBody();
      if (data.hasOwnProperty('model'))
        obj.model = ApiClient.convertToType(data['model'], 'String');
      if (data.hasOwnProperty('messages'))
        obj.messages = ApiClient.convertToType(data['messages'], [ChatcompletionsMessages]);
      if (data.hasOwnProperty('tools'))
        obj.tools = ChatcompletionsTools.constructFromObject(data['tools']);
      if (data.hasOwnProperty('stream'))
        obj.stream = ApiClient.convertToType(data['stream'], 'Boolean');
    }
    return obj;
  }
}

/**
 * The mAIstro agent to call
 * @member {String} model
 */
ChatCompletionsBody.prototype.model = undefined;

/**
 * @member {Array.<module:model/ChatcompletionsMessages>} messages
 */
ChatCompletionsBody.prototype.messages = undefined;

/**
 * @member {module:model/ChatcompletionsTools} tools
 */
ChatCompletionsBody.prototype.tools = undefined;

/**
 * Whether to stream responses as server-sent events
 * @member {Boolean} stream
 */
ChatCompletionsBody.prototype.stream = undefined;

