/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ChatcompletionsMessages model module.
 * @module model/ChatcompletionsMessages
 * @version 1.0.1
 */
export default class ChatcompletionsMessages {
  /**
   * Constructs a new <code>ChatcompletionsMessages</code>.
   * @alias module:model/ChatcompletionsMessages
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ChatcompletionsMessages</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChatcompletionsMessages} obj Optional instance to populate.
   * @return {module:model/ChatcompletionsMessages} The populated <code>ChatcompletionsMessages</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ChatcompletionsMessages();
      if (data.hasOwnProperty('role'))
        obj.role = ApiClient.convertToType(data['role'], 'String');
      if (data.hasOwnProperty('content'))
        obj.content = ApiClient.convertToType(data['content'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>role</code> property.
 * @enum {String}
 * @readonly
 */
ChatcompletionsMessages.RoleEnum = {
  /**
   * value: "user"
   * @const
   */
  user: "user",

  /**
   * value: "assistant"
   * @const
   */
  assistant: "assistant",

  /**
   * value: "system"
   * @const
   */
  system: "system",

  /**
   * value: "tool"
   * @const
   */
  tool: "tool"
};
/**
 * The role of the message sender
 * @member {module:model/ChatcompletionsMessages.RoleEnum} role
 */
ChatcompletionsMessages.prototype.role = undefined;

/**
 * The content of the message
 * @member {String} content
 */
ChatcompletionsMessages.prototype.content = undefined;

