/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import SeekStreamParams from './SeekStreamParams';

/**
 * The ChatcompletionsTools model module.
 * @module model/ChatcompletionsTools
 * @version 1.0.1
 */
export default class ChatcompletionsTools {
  /**
   * Constructs a new <code>ChatcompletionsTools</code>.
   * @alias module:model/ChatcompletionsTools
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ChatcompletionsTools</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChatcompletionsTools} obj Optional instance to populate.
   * @return {module:model/ChatcompletionsTools} The populated <code>ChatcompletionsTools</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ChatcompletionsTools();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('params'))
        obj.params = ApiClient.convertToType(data['params'], [SeekStreamParams]);
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
ChatcompletionsTools.TypeEnum = {
  /**
   * value: "agent"
   * @const
   */
  agent: "agent"
};
/**
 * The type of tool to call. Only \"agent\" is valid
 * @member {module:model/ChatcompletionsTools.TypeEnum} type
 */
ChatcompletionsTools.prototype.type = undefined;

/**
 * An array of parameters to use when calling the mAIstro agent\"
 * @member {Array.<module:model/SeekStreamParams>} params
 */
ChatcompletionsTools.prototype.params = undefined;

