/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ExtractBody model module.
 * @module model/ExtractBody
 * @version 1.0.1
 */
export default class ExtractBody {
  /**
   * Constructs a new <code>ExtractBody</code>.
   * @alias module:model/ExtractBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ExtractBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExtractBody} obj Optional instance to populate.
   * @return {module:model/ExtractBody} The populated <code>ExtractBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ExtractBody();
      if (data.hasOwnProperty('text'))
        obj.text = ApiClient.convertToType(data['text'], 'String');
      if (data.hasOwnProperty('language'))
        obj.language = ApiClient.convertToType(data['language'], 'String');
      if (data.hasOwnProperty('entities'))
        obj.entities = ApiClient.convertToType(data['entities'], 'String');
      if (data.hasOwnProperty('slots'))
        obj.slots = ApiClient.convertToType(data['slots'], Object);
      if (data.hasOwnProperty('confirmSlots'))
        obj.confirmSlots = ApiClient.convertToType(data['confirmSlots'], 'Boolean');
      if (data.hasOwnProperty('confirmEverySlot'))
        obj.confirmEverySlot = ApiClient.convertToType(data['confirmEverySlot'], 'Boolean');
    }
    return obj;
  }
}

/**
 * The text to extract entitites from
 * @member {String} text
 */
ExtractBody.prototype.text = undefined;

/**
 * The 2-char language code to be used when generating a promptEntity response. Only set this if you want to override the configured language in NeuralSeek.
 * @member {String} language
 */
ExtractBody.prototype.language = undefined;

/**
 * An array of objects, stringified. The properties of the object are name, description, and format
 * @member {String} entities
 */
ExtractBody.prototype.entities = undefined;

/**
 * Provide an object of variable names, with a type property set to an entity type to match to in total across multiple turns of a conversation. NeuralSeek will return a promptEntity to display to the user to continue to fil the slots.  As slots are filled the value field will be populated.  Continue to send this entire filed back as input thru the multiple turns of the conversation, untill Complete is set to true.  Complete will be set to true when all slots are filled
 * @member {Object} slots
 */
ExtractBody.prototype.slots = undefined;

/**
 * When using Slots, once all slots have been filled display a summary and ask for a confirmation before setting the 'complete' flag
 * @member {Boolean} confirmSlots
 */
ExtractBody.prototype.confirmSlots = undefined;

/**
 * When using Slots, on every turn recite the slot that was just previously filled.
 * @member {Boolean} confirmEverySlot
 */
ExtractBody.prototype.confirmEverySlot = undefined;

