/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The IdentifysingleBody model module.
 * @module model/IdentifysingleBody
 * @version 1.0.1
 */
export default class IdentifysingleBody {
  /**
   * Constructs a new <code>IdentifysingleBody</code>.
   * @alias module:model/IdentifysingleBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IdentifysingleBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IdentifysingleBody} obj Optional instance to populate.
   * @return {module:model/IdentifysingleBody} The populated <code>IdentifysingleBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IdentifysingleBody();
      if (data.hasOwnProperty('input'))
        obj.input = ApiClient.convertToType(data['input'], 'String');
    }
    return obj;
  }
}

/**
 * The input text to identify the language of
 * @member {String} input
 * @default ''
 */
IdentifysingleBody.prototype.input = '';

