/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The InlineResponse2004Message model module.
 * @module model/InlineResponse2004Message
 * @version 1.0.1
 */
export default class InlineResponse2004Message {
  /**
   * Constructs a new <code>InlineResponse2004Message</code>.
   * @alias module:model/InlineResponse2004Message
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2004Message</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2004Message} obj Optional instance to populate.
   * @return {module:model/InlineResponse2004Message} The populated <code>InlineResponse2004Message</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2004Message();
      if (data.hasOwnProperty('role'))
        obj.role = ApiClient.convertToType(data['role'], 'String');
      if (data.hasOwnProperty('content'))
        obj.content = ApiClient.convertToType(data['content'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>role</code> property.
 * @enum {String}
 * @readonly
 */
InlineResponse2004Message.RoleEnum = {
  /**
   * value: "user"
   * @const
   */
  user: "user",

  /**
   * value: "assistant"
   * @const
   */
  assistant: "assistant"
};
/**
 * The role of the message sender
 * @member {module:model/InlineResponse2004Message.RoleEnum} role
 */
InlineResponse2004Message.prototype.role = undefined;

/**
 * The content of the message
 * @member {String} content
 */
InlineResponse2004Message.prototype.content = undefined;

