/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import InlineResponse2004Choices from './InlineResponse2004Choices';

/**
 * The InlineResponse2004 model module.
 * @module model/InlineResponse2004
 * @version 1.0.1
 */
export default class InlineResponse2004 {
  /**
   * Constructs a new <code>InlineResponse2004</code>.
   * @alias module:model/InlineResponse2004
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2004</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2004} obj Optional instance to populate.
   * @return {module:model/InlineResponse2004} The populated <code>InlineResponse2004</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2004();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('object'))
        obj._object = ApiClient.convertToType(data['object'], 'String');
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Number');
      if (data.hasOwnProperty('model'))
        obj.model = ApiClient.convertToType(data['model'], 'String');
      if (data.hasOwnProperty('choices'))
        obj.choices = ApiClient.convertToType(data['choices'], [InlineResponse2004Choices]);
    }
    return obj;
  }
}

/**
 * Unique identifier for the completion
 * @member {String} id
 */
InlineResponse2004.prototype.id = undefined;

/**
 * The type of object returned, should be 'chat.completion'
 * @member {String} _object
 */
InlineResponse2004.prototype._object = undefined;

/**
 * Timestamp of when the completion was created
 * @member {Number} created
 */
InlineResponse2004.prototype.created = undefined;

/**
 * The model used for generating the completion
 * @member {String} model
 */
InlineResponse2004.prototype.model = undefined;

/**
 * @member {Array.<module:model/InlineResponse2004Choices>} choices
 */
InlineResponse2004.prototype.choices = undefined;

