/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The InlineResponse2002Render model module.
 * @module model/InlineResponse2002Render
 * @version 1.0.1
 */
export default class InlineResponse2002Render {
  /**
   * Constructs a new <code>InlineResponse2002Render</code>.
   * @alias module:model/InlineResponse2002Render
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2002Render</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2002Render} obj Optional instance to populate.
   * @return {module:model/InlineResponse2002Render} The populated <code>InlineResponse2002Render</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2002Render();
      if (data.hasOwnProperty('node'))
        obj.node = ApiClient.convertToType(data['node'], 'String');
      if (data.hasOwnProperty('vars'))
        obj.vars = ApiClient.convertToType(data['vars'], Object);
      if (data.hasOwnProperty('out'))
        obj.out = ApiClient.convertToType(data['out'], 'String');
      if (data.hasOwnProperty('chained'))
        obj.chained = ApiClient.convertToType(data['chained'], 'Boolean');
    }
    return obj;
  }
}

/**
 * The node type
 * @member {String} node
 * @default ''
 */
InlineResponse2002Render.prototype.node = '';

/**
 * The variable values
 * @member {Object} vars
 */
InlineResponse2002Render.prototype.vars = undefined;

/**
 * The output
 * @member {String} out
 * @default ''
 */
InlineResponse2002Render.prototype.out = '';

/**
 * True if the step is chained
 * @member {Boolean} chained
 */
InlineResponse2002Render.prototype.chained = undefined;

