/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import InlineResponse2005TopIntents from './InlineResponse2005TopIntents';

/**
 * The InlineResponse2005 model module.
 * @module model/InlineResponse2005
 * @version 1.0.1
 */
export default class InlineResponse2005 {
  /**
   * Constructs a new <code>InlineResponse2005</code>.
   * @alias module:model/InlineResponse2005
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2005</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2005} obj Optional instance to populate.
   * @return {module:model/InlineResponse2005} The populated <code>InlineResponse2005</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2005();
      if (data.hasOwnProperty('intent'))
        obj.intent = ApiClient.convertToType(data['intent'], 'String');
      if (data.hasOwnProperty('category'))
        obj.category = ApiClient.convertToType(data['category'], 'String');
      if (data.hasOwnProperty('categoryId'))
        obj.categoryId = ApiClient.convertToType(data['categoryId'], 'Number');
      if (data.hasOwnProperty('topIntents'))
        obj.topIntents = InlineResponse2005TopIntents.constructFromObject(data['topIntents']);
    }
    return obj;
  }
}

/**
 * The matched Intent
 * @member {String} intent
 * @default ''
 */
InlineResponse2005.prototype.intent = '';

/**
 * The matched Category
 * @member {String} category
 * @default ''
 */
InlineResponse2005.prototype.category = '';

/**
 * The Category id
 * @member {Number} categoryId
 */
InlineResponse2005.prototype.categoryId = undefined;

/**
 * @member {module:model/InlineResponse2005TopIntents} topIntents
 */
InlineResponse2005.prototype.topIntents = undefined;

