/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The InlineResponse2005TopIntents model module.
 * @module model/InlineResponse2005TopIntents
 * @version 1.0.1
 */
export default class InlineResponse2005TopIntents {
  /**
   * Constructs a new <code>InlineResponse2005TopIntents</code>.
   * If Vector Similarity is set as the Intent Match type, this will provide the top 3 matches
   * @alias module:model/InlineResponse2005TopIntents
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2005TopIntents</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2005TopIntents} obj Optional instance to populate.
   * @return {module:model/InlineResponse2005TopIntents} The populated <code>InlineResponse2005TopIntents</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2005TopIntents();
      if (data.hasOwnProperty('score'))
        obj.score = ApiClient.convertToType(data['score'], 'Number');
      if (data.hasOwnProperty('intent'))
        obj.intent = ApiClient.convertToType(data['intent'], 'String');
    }
    return obj;
  }
}

/**
 * The score of the intent
 * @member {Number} score
 */
InlineResponse2005TopIntents.prototype.score = undefined;

/**
 * The intent name
 * @member {String} intent
 * @default ''
 */
InlineResponse2005TopIntents.prototype.intent = '';

