/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The InlineResponse2006ExtractedEntities model module.
 * @module model/InlineResponse2006ExtractedEntities
 * @version 1.0.1
 */
export default class InlineResponse2006ExtractedEntities {
  /**
   * Constructs a new <code>InlineResponse2006ExtractedEntities</code>.
   * @alias module:model/InlineResponse2006ExtractedEntities
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2006ExtractedEntities</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2006ExtractedEntities} obj Optional instance to populate.
   * @return {module:model/InlineResponse2006ExtractedEntities} The populated <code>InlineResponse2006ExtractedEntities</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2006ExtractedEntities();
      if (data.hasOwnProperty('entity'))
        obj.entity = ApiClient.convertToType(data['entity'], 'String');
    }
    return obj;
  }
}

/**
 * The found entity
 * @member {String} entity
 * @default ''
 */
InlineResponse2006ExtractedEntities.prototype.entity = '';

