/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The InlineResponse2007Translations model module.
 * @module model/InlineResponse2007Translations
 * @version 1.0.1
 */
export default class InlineResponse2007Translations {
  /**
   * Constructs a new <code>InlineResponse2007Translations</code>.
   * @alias module:model/InlineResponse2007Translations
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2007Translations</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2007Translations} obj Optional instance to populate.
   * @return {module:model/InlineResponse2007Translations} The populated <code>InlineResponse2007Translations</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2007Translations();
      if (data.hasOwnProperty('translation'))
        obj.translation = ApiClient.convertToType(data['translation'], 'String');
    }
    return obj;
  }
}

/**
 * The translation
 * @member {String} translation
 * @default ''
 */
InlineResponse2007Translations.prototype.translation = '';

