/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import InlineResponse2007Translations from './InlineResponse2007Translations';

/**
 * The InlineResponse2007 model module.
 * @module model/InlineResponse2007
 * @version 1.0.1
 */
export default class InlineResponse2007 {
  /**
   * Constructs a new <code>InlineResponse2007</code>.
   * @alias module:model/InlineResponse2007
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2007</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2007} obj Optional instance to populate.
   * @return {module:model/InlineResponse2007} The populated <code>InlineResponse2007</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2007();
      if (data.hasOwnProperty('word_count'))
        obj.wordCount = ApiClient.convertToType(data['word_count'], 'Number');
      if (data.hasOwnProperty('character_count'))
        obj.characterCount = ApiClient.convertToType(data['character_count'], 'Number');
      if (data.hasOwnProperty('detected_language'))
        obj.detectedLanguage = ApiClient.convertToType(data['detected_language'], 'String');
      if (data.hasOwnProperty('detected_language_confidence'))
        obj.detectedLanguageConfidence = ApiClient.convertToType(data['detected_language_confidence'], 'Number');
      if (data.hasOwnProperty('translation_glossary'))
        obj.translationGlossary = ApiClient.convertToType(data['translation_glossary'], 'Boolean');
      if (data.hasOwnProperty('translation_glossary_exact'))
        obj.translationGlossaryExact = ApiClient.convertToType(data['translation_glossary_exact'], 'Boolean');
      if (data.hasOwnProperty('translations'))
        obj.translations = ApiClient.convertToType(data['translations'], [InlineResponse2007Translations]);
    }
    return obj;
  }
}

/**
 * The word count.
 * @member {Number} wordCount
 */
InlineResponse2007.prototype.wordCount = undefined;

/**
 * The word count.
 * @member {Number} characterCount
 */
InlineResponse2007.prototype.characterCount = undefined;

/**
 * The 2-digit language code for the detected language.
 * @member {String} detectedLanguage
 * @default ''
 */
InlineResponse2007.prototype.detectedLanguage = '';

/**
 * The detected language confidence.
 * @member {Number} detectedLanguageConfidence
 */
InlineResponse2007.prototype.detectedLanguageConfidence = undefined;

/**
 * Returns true if a glossary is loaded and matched any input.
 * @member {Boolean} translationGlossary
 */
InlineResponse2007.prototype.translationGlossary = undefined;

/**
 * Returns true if a glossary is loaded and an entry exactly matched the input.
 * @member {Boolean} translationGlossaryExact
 */
InlineResponse2007.prototype.translationGlossaryExact = undefined;

/**
 * @member {Array.<module:model/InlineResponse2007Translations>} translations
 */
InlineResponse2007.prototype.translations = undefined;

