/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import InlineResponse2002Render from './InlineResponse2002Render';
import SeekResponseVariablesExpanded from './SeekResponseVariablesExpanded';

/**
 * The InlineResponse2002 model module.
 * @module model/InlineResponse2002
 * @version 1.0.1
 */
export default class InlineResponse2002 {
  /**
   * Constructs a new <code>InlineResponse2002</code>.
   * @alias module:model/InlineResponse2002
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2002</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2002} obj Optional instance to populate.
   * @return {module:model/InlineResponse2002} The populated <code>InlineResponse2002</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2002();
      if (data.hasOwnProperty('answer'))
        obj.answer = ApiClient.convertToType(data['answer'], 'String');
      if (data.hasOwnProperty('sourceParts'))
        obj.sourceParts = ApiClient.convertToType(data['sourceParts'], ['String']);
      if (data.hasOwnProperty('render'))
        obj.render = ApiClient.convertToType(data['render'], [InlineResponse2002Render]);
      if (data.hasOwnProperty('variables'))
        obj.variables = ApiClient.convertToType(data['variables'], Object);
      if (data.hasOwnProperty('variablesExpanded'))
        obj.variablesExpanded = ApiClient.convertToType(data['variablesExpanded'], [SeekResponseVariablesExpanded]);
    }
    return obj;
  }
}

/**
 * The generated response
 * @member {String} answer
 * @default ''
 */
InlineResponse2002.prototype.answer = '';

/**
 * @member {Array.<String>} sourceParts
 */
InlineResponse2002.prototype.sourceParts = undefined;

/**
 * The steps used to render the result.
 * @member {Array.<module:model/InlineResponse2002Render>} render
 */
InlineResponse2002.prototype.render = undefined;

/**
 * The returned variable.
 * @member {Object} variables
 */
InlineResponse2002.prototype.variables = undefined;

/**
 * The returned variable, in the format of the input params
 * @member {Array.<module:model/SeekResponseVariablesExpanded>} variablesExpanded
 */
InlineResponse2002.prototype.variablesExpanded = undefined;

