/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import InlineResponse2004Message from './InlineResponse2004Message';

/**
 * The InlineResponse2004Choices model module.
 * @module model/InlineResponse2004Choices
 * @version 1.0.1
 */
export default class InlineResponse2004Choices {
  /**
   * Constructs a new <code>InlineResponse2004Choices</code>.
   * @alias module:model/InlineResponse2004Choices
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2004Choices</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2004Choices} obj Optional instance to populate.
   * @return {module:model/InlineResponse2004Choices} The populated <code>InlineResponse2004Choices</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2004Choices();
      if (data.hasOwnProperty('index'))
        obj.index = ApiClient.convertToType(data['index'], 'Number');
      if (data.hasOwnProperty('message'))
        obj.message = InlineResponse2004Message.constructFromObject(data['message']);
      if (data.hasOwnProperty('finish_reason'))
        obj.finishReason = ApiClient.convertToType(data['finish_reason'], 'String');
    }
    return obj;
  }
}

/**
 * The index of the choice
 * @member {Number} index
 */
InlineResponse2004Choices.prototype.index = undefined;

/**
 * @member {module:model/InlineResponse2004Message} message
 */
InlineResponse2004Choices.prototype.message = undefined;

/**
 * The reason the message generation finished
 * @member {String} finishReason
 */
InlineResponse2004Choices.prototype.finishReason = undefined;

