/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import InlineResponse2006ExtractedEntities from './InlineResponse2006ExtractedEntities';

/**
 * The InlineResponse2006 model module.
 * @module model/InlineResponse2006
 * @version 1.0.1
 */
export default class InlineResponse2006 {
  /**
   * Constructs a new <code>InlineResponse2006</code>.
   * @alias module:model/InlineResponse2006
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2006</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2006} obj Optional instance to populate.
   * @return {module:model/InlineResponse2006} The populated <code>InlineResponse2006</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2006();
      if (data.hasOwnProperty('extractedEntities'))
        obj.extractedEntities = ApiClient.convertToType(data['extractedEntities'], [InlineResponse2006ExtractedEntities]);
      if (data.hasOwnProperty('complete'))
        obj.complete = ApiClient.convertToType(data['complete'], 'Boolean');
      if (data.hasOwnProperty('promptEntity'))
        obj.promptEntity = ApiClient.convertToType(data['promptEntity'], 'String');
      if (data.hasOwnProperty('slots'))
        obj.slots = ApiClient.convertToType(data['slots'], Object);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/InlineResponse2006ExtractedEntities>} extractedEntities
 */
InlineResponse2006.prototype.extractedEntities = undefined;

/**
 * If slots are passed, complete will be set to true when all slots are filled
 * @member {Boolean} complete
 * @default false
 */
InlineResponse2006.prototype.complete = false;

/**
 * A message to display to the user asking them to provide input for the next group of unfilled slots.
 * @member {String} promptEntity
 */
InlineResponse2006.prototype.promptEntity = undefined;

/**
 * If the slots parameter is filled on the input, NeuralSeek will return it and begin filling the value fields. Continue to send this entire filed back as input thru the multiple turns of the conversation, untill Complete is set to true.  Complete will be set to true when all slots are filled
 * @member {Object} slots
 */
InlineResponse2006.prototype.slots = undefined;

