/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The LogExternalAgentEntries model module.
 * @module model/LogExternalAgentEntries
 * @version 1.0.1
 */
export default class LogExternalAgentEntries {
  /**
   * Constructs a new <code>LogExternalAgentEntries</code>.
   * @alias module:model/LogExternalAgentEntries
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>LogExternalAgentEntries</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LogExternalAgentEntries} obj Optional instance to populate.
   * @return {module:model/LogExternalAgentEntries} The populated <code>LogExternalAgentEntries</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LogExternalAgentEntries();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('llmtime'))
        obj.llmtime = ApiClient.convertToType(data['llmtime'], 'Number');
      if (data.hasOwnProperty('inputtokencount'))
        obj.inputtokencount = ApiClient.convertToType(data['inputtokencount'], 'Number');
      if (data.hasOwnProperty('generatedtokencount'))
        obj.generatedtokencount = ApiClient.convertToType(data['generatedtokencount'], 'Number');
      if (data.hasOwnProperty('llm'))
        obj.llm = ApiClient.convertToType(data['llm'], 'String');
      if (data.hasOwnProperty('llmcode'))
        obj.llmcode = ApiClient.convertToType(data['llmcode'], 'String');
      if (data.hasOwnProperty('kbtime'))
        obj.kbtime = ApiClient.convertToType(data['kbtime'], 'Number');
      if (data.hasOwnProperty('kb'))
        obj.kb = ApiClient.convertToType(data['kb'], 'String');
      if (data.hasOwnProperty('kbScore'))
        obj.kbScore = ApiClient.convertToType(data['kbScore'], 'Number');
      if (data.hasOwnProperty('kbCoverage'))
        obj.kbCoverage = ApiClient.convertToType(data['kbCoverage'], 'Number');
      if (data.hasOwnProperty('elementTime'))
        obj.elementTime = ApiClient.convertToType(data['elementTime'], 'Number');
      if (data.hasOwnProperty('element'))
        obj.element = ApiClient.convertToType(data['element'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
LogExternalAgentEntries.TypeEnum = {
  /**
   * value: "LLMTime"
   * @const
   */
  lLMTime: "LLMTime",

  /**
   * value: "LLMCacheTime"
   * @const
   */
  lLMCacheTime: "LLMCacheTime",

  /**
   * value: "KBTime"
   * @const
   */
  kBTime: "KBTime",

  /**
   * value: "ElementTime"
   * @const
   */
  elementTime: "ElementTime"
};
/**
 * @member {module:model/LogExternalAgentEntries.TypeEnum} type
 */
LogExternalAgentEntries.prototype.type = undefined;

/**
 * The LLM time in ms
 * @member {Number} llmtime
 */
LogExternalAgentEntries.prototype.llmtime = undefined;

/**
 * Number of input tokens
 * @member {Number} inputtokencount
 */
LogExternalAgentEntries.prototype.inputtokencount = undefined;

/**
 * Number of generated tokens
 * @member {Number} generatedtokencount
 */
LogExternalAgentEntries.prototype.generatedtokencount = undefined;

/**
 * LLM model identifier
 * @member {String} llm
 */
LogExternalAgentEntries.prototype.llm = undefined;

/**
 * LLM specific code
 * @member {String} llmcode
 */
LogExternalAgentEntries.prototype.llmcode = undefined;

/**
 * Knowledge base processing time in ms
 * @member {Number} kbtime
 */
LogExternalAgentEntries.prototype.kbtime = undefined;

/**
 * Knowledge base identifier
 * @member {String} kb
 */
LogExternalAgentEntries.prototype.kb = undefined;

/**
 * Knowledge base relevance score
 * @member {Number} kbScore
 */
LogExternalAgentEntries.prototype.kbScore = undefined;

/**
 * Knowledge base coverage percentage
 * @member {Number} kbCoverage
 */
LogExternalAgentEntries.prototype.kbCoverage = undefined;

/**
 * Time taken for element processing in ms
 * @member {Number} elementTime
 */
LogExternalAgentEntries.prototype.elementTime = undefined;

/**
 * Allowed values for the <code>element</code> property.
 * @enum {String}
 * @readonly
 */
LogExternalAgentEntries.ElementEnum = {
  /**
   * value: "model"
   * @const
   */
  model: "model",

  /**
   * value: "rest"
   * @const
   */
  rest: "rest",

  /**
   * value: "database"
   * @const
   */
  database: "database"
};
/**
 * Type of element being timed
 * @member {module:model/LogExternalAgentEntries.ElementEnum} element
 */
LogExternalAgentEntries.prototype.element = undefined;

