/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import LogExternalAgentEntries from './LogExternalAgentEntries';

/**
 * The LogExternalAgentBody model module.
 * @module model/LogExternalAgentBody
 * @version 1.0.1
 */
export default class LogExternalAgentBody {
  /**
   * Constructs a new <code>LogExternalAgentBody</code>.
   * @alias module:model/LogExternalAgentBody
   * @class
   * @param runId {Number} Unique numeric identifier for the execution run
   * @param templateName {String} Name of the Agent being executed
   * @param user {String} User identifier who initiated the execution
   * @param resultsLink {String} Link to detailed execution results
   * @param entries {Array.<module:model/LogExternalAgentEntries>} 
   */
  constructor(runId, templateName, user, resultsLink, entries) {
    this.runId = runId;
    this.templateName = templateName;
    this.user = user;
    this.resultsLink = resultsLink;
    this.entries = entries;
  }

  /**
   * Constructs a <code>LogExternalAgentBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LogExternalAgentBody} obj Optional instance to populate.
   * @return {module:model/LogExternalAgentBody} The populated <code>LogExternalAgentBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LogExternalAgentBody();
      if (data.hasOwnProperty('runId'))
        obj.runId = ApiClient.convertToType(data['runId'], 'Number');
      if (data.hasOwnProperty('templateName'))
        obj.templateName = ApiClient.convertToType(data['templateName'], 'String');
      if (data.hasOwnProperty('user'))
        obj.user = ApiClient.convertToType(data['user'], 'String');
      if (data.hasOwnProperty('time'))
        obj.time = ApiClient.convertToType(data['time'], 'Number');
      if (data.hasOwnProperty('resultsLink'))
        obj.resultsLink = ApiClient.convertToType(data['resultsLink'], 'String');
      if (data.hasOwnProperty('entries'))
        obj.entries = ApiClient.convertToType(data['entries'], [LogExternalAgentEntries]);
    }
    return obj;
  }
}

/**
 * Unique numeric identifier for the execution run
 * @member {Number} runId
 */
LogExternalAgentBody.prototype.runId = undefined;

/**
 * Name of the Agent being executed
 * @member {String} templateName
 */
LogExternalAgentBody.prototype.templateName = undefined;

/**
 * User identifier who initiated the execution
 * @member {String} user
 */
LogExternalAgentBody.prototype.user = undefined;

/**
 * The total time of the Agent run in ms
 * @member {Number} time
 */
LogExternalAgentBody.prototype.time = undefined;

/**
 * Link to detailed execution results
 * @member {String} resultsLink
 */
LogExternalAgentBody.prototype.resultsLink = undefined;

/**
 * @member {Array.<module:model/LogExternalAgentEntries>} entries
 */
LogExternalAgentBody.prototype.entries = undefined;

