/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The LogsBody model module.
 * @module model/LogsBody
 * @version 1.0.1
 */
export default class LogsBody {
  /**
   * Constructs a new <code>LogsBody</code>.
   * @alias module:model/LogsBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>LogsBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LogsBody} obj Optional instance to populate.
   * @return {module:model/LogsBody} The populated <code>LogsBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LogsBody();
      if (data.hasOwnProperty('limit'))
        obj.limit = ApiClient.convertToType(data['limit'], 'Number');
      if (data.hasOwnProperty('skip'))
        obj.skip = ApiClient.convertToType(data['skip'], 'Number');
      if (data.hasOwnProperty('search'))
        obj.search = ApiClient.convertToType(data['search'], 'String');
    }
    return obj;
  }
}

/**
 * The number of rows to return, max of 100
 * @member {Number} limit
 * @default 100
 */
LogsBody.prototype.limit = 100;

/**
 * The number of result sets to skip for paging
 * @member {Number} skip
 * @default 0
 */
LogsBody.prototype.skip = 0;

/**
 * An optional search string
 * @member {String} search
 * @default ''
 */
LogsBody.prototype.search = '';

