/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The MaistroRateBody model module.
 * @module model/MaistroRateBody
 * @version 1.0.1
 */
export default class MaistroRateBody {
  /**
   * Constructs a new <code>MaistroRateBody</code>.
   * @alias module:model/MaistroRateBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MaistroRateBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MaistroRateBody} obj Optional instance to populate.
   * @return {module:model/MaistroRateBody} The populated <code>MaistroRateBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MaistroRateBody();
      if (data.hasOwnProperty('agent'))
        obj.agent = ApiClient.convertToType(data['agent'], 'String');
      if (data.hasOwnProperty('runId'))
        obj.runId = ApiClient.convertToType(data['runId'], 'Number');
      if (data.hasOwnProperty('score'))
        obj.score = ApiClient.convertToType(data['score'], 'Number');
      if (data.hasOwnProperty('feedback'))
        obj.feedback = ApiClient.convertToType(data['feedback'], 'String');
    }
    return obj;
  }
}

/**
 * The Agent
 * @member {String} agent
 */
MaistroRateBody.prototype.agent = undefined;

/**
 * The runId
 * @member {Number} runId
 */
MaistroRateBody.prototype.runId = undefined;

/**
 * The rating score. An integer, 0-5. 0 is worst, 5 is best.  For Thumbs up / Thumbs down send 0 or 5
 * @member {Number} score
 */
MaistroRateBody.prototype.score = undefined;

/**
 * text feedback on the answer
 * @member {String} feedback
 */
MaistroRateBody.prototype.feedback = undefined;

