/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The MaistroRatingsBody model module.
 * @module model/MaistroRatingsBody
 * @version 1.0.1
 */
export default class MaistroRatingsBody {
  /**
   * Constructs a new <code>MaistroRatingsBody</code>.
   * @alias module:model/MaistroRatingsBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MaistroRatingsBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MaistroRatingsBody} obj Optional instance to populate.
   * @return {module:model/MaistroRatingsBody} The populated <code>MaistroRatingsBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MaistroRatingsBody();
      if (data.hasOwnProperty('agent'))
        obj.agent = ApiClient.convertToType(data['agent'], 'String');
      if (data.hasOwnProperty('number'))
        obj._number = ApiClient.convertToType(data['number'], 'Number');
    }
    return obj;
  }
}

/**
 * The agent
 * @member {String} agent
 */
MaistroRatingsBody.prototype.agent = undefined;

/**
 * The number of previous user ratings to average. Leave blank to average all ratings.
 * @member {Number} _number
 */
MaistroRatingsBody.prototype._number = undefined;

