/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import SeekStreamOptionsLastTurn from './SeekStreamOptionsLastTurn';

/**
 * The MaistroOptions model module.
 * @module model/MaistroOptions
 * @version 1.0.1
 */
export default class MaistroOptions {
  /**
   * Constructs a new <code>MaistroOptions</code>.
   * Override options
   * @alias module:model/MaistroOptions
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MaistroOptions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MaistroOptions} obj Optional instance to populate.
   * @return {module:model/MaistroOptions} The populated <code>MaistroOptions</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MaistroOptions();
      if (data.hasOwnProperty('streaming'))
        obj.streaming = ApiClient.convertToType(data['streaming'], 'Boolean');
      if (data.hasOwnProperty('llm'))
        obj.llm = ApiClient.convertToType(data['llm'], 'String');
      if (data.hasOwnProperty('user_id'))
        obj.userId = ApiClient.convertToType(data['user_id'], 'String');
      if (data.hasOwnProperty('timeout'))
        obj.timeout = ApiClient.convertToType(data['timeout'], 'Number');
      if (data.hasOwnProperty('temperatureMod'))
        obj.temperatureMod = ApiClient.convertToType(data['temperatureMod'], 'Number');
      if (data.hasOwnProperty('toppMod'))
        obj.toppMod = ApiClient.convertToType(data['toppMod'], 'Number');
      if (data.hasOwnProperty('freqpenaltyMod'))
        obj.freqpenaltyMod = ApiClient.convertToType(data['freqpenaltyMod'], 'Number');
      if (data.hasOwnProperty('minTokens'))
        obj.minTokens = ApiClient.convertToType(data['minTokens'], 'Number');
      if (data.hasOwnProperty('maxTokens'))
        obj.maxTokens = ApiClient.convertToType(data['maxTokens'], 'Number');
      if (data.hasOwnProperty('lastTurn'))
        obj.lastTurn = ApiClient.convertToType(data['lastTurn'], [SeekStreamOptionsLastTurn]);
      if (data.hasOwnProperty('returnVariables'))
        obj.returnVariables = ApiClient.convertToType(data['returnVariables'], 'Boolean');
      if (data.hasOwnProperty('returnVariablesExpanded'))
        obj.returnVariablesExpanded = ApiClient.convertToType(data['returnVariablesExpanded'], 'Boolean');
      if (data.hasOwnProperty('returnRender'))
        obj.returnRender = ApiClient.convertToType(data['returnRender'], 'Boolean');
      if (data.hasOwnProperty('returnSource'))
        obj.returnSource = ApiClient.convertToType(data['returnSource'], 'Boolean');
      if (data.hasOwnProperty('maxRecursion'))
        obj.maxRecursion = ApiClient.convertToType(data['maxRecursion'], 'Number');
    }
    return obj;
  }
}

/**
 * Return the response via SSE streaming.  This is not compatible with most Virtual Agent platforms, and is intentded for direct website use.
 * @member {Boolean} streaming
 * @default false
 */
MaistroOptions.prototype.streaming = false;

/**
 * Override the LLM load balancer and force seek to use a specific LLM.  Input the LLM code here.  You must have a valid model card set up on the configure tab for the code you input.
 * @member {String} llm
 * @default ''
 */
MaistroOptions.prototype.llm = '';

/**
 * Set the user_id. Useful and required if you have a corporate document filter set
 * @member {String} userId
 * @default ''
 */
MaistroOptions.prototype.userId = '';

/**
 * Timeout in miliseconds. (optional)
 * @member {Number} timeout
 */
MaistroOptions.prototype.timeout = undefined;

/**
 * Shift the model's baseline temperature weighting by a percentage
 * @member {Number} temperatureMod
 */
MaistroOptions.prototype.temperatureMod = undefined;

/**
 * Shift the model's baseline probability weighting by a percentage
 * @member {Number} toppMod
 */
MaistroOptions.prototype.toppMod = undefined;

/**
 * Shift the model's baseline frequency penalty weighting by a percentage
 * @member {Number} freqpenaltyMod
 */
MaistroOptions.prototype.freqpenaltyMod = undefined;

/**
 * Set the minimum tokens you  want the model to produce
 * @member {Number} minTokens
 */
MaistroOptions.prototype.minTokens = undefined;

/**
 * Set the maximum tokens you  want the model to produce
 * @member {Number} maxTokens
 */
MaistroOptions.prototype.maxTokens = undefined;

/**
 * lastTurn is a flexible object. It is backwards compatible with the original single turn object, as well as compatible with the Watson Assistant session history format.
 * @member {Array.<module:model/SeekStreamOptionsLastTurn>} lastTurn
 */
MaistroOptions.prototype.lastTurn = undefined;

/**
 * Return the final state of all variables in a dense object
 * @member {Boolean} returnVariables
 * @default false
 */
MaistroOptions.prototype.returnVariables = false;

/**
 * Return the final state of all variables in the same format as the input params
 * @member {Boolean} returnVariablesExpanded
 * @default false
 */
MaistroOptions.prototype.returnVariablesExpanded = false;

/**
 * Return the midstate renders
 * @member {Boolean} returnRender
 * @default false
 */
MaistroOptions.prototype.returnRender = false;

/**
 * Return the source parts
 * @member {Boolean} returnSource
 * @default false
 */
MaistroOptions.prototype.returnSource = false;

/**
 * The maximum number of recursive calls to Explore.  Use caution that you have not created an endless loop as you increase the maximum, as each Explore is charged.
 * @member {Number} maxRecursion
 * @default 10
 */
MaistroOptions.prototype.maxRecursion = 10;

