/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import MaistroOptions from './MaistroOptions';
import SeekStreamParams from './SeekStreamParams';

/**
 * The MaistroBody model module.
 * @module model/MaistroBody
 * @version 1.0.1
 */
export default class MaistroBody {
  /**
   * Constructs a new <code>MaistroBody</code>.
   * @alias module:model/MaistroBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MaistroBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MaistroBody} obj Optional instance to populate.
   * @return {module:model/MaistroBody} The populated <code>MaistroBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MaistroBody();
      if (data.hasOwnProperty('ntl'))
        obj.ntl = ApiClient.convertToType(data['ntl'], 'String');
      if (data.hasOwnProperty('agent'))
        obj.agent = ApiClient.convertToType(data['agent'], 'String');
      if (data.hasOwnProperty('params'))
        obj.params = ApiClient.convertToType(data['params'], [SeekStreamParams]);
      if (data.hasOwnProperty('options'))
        obj.options = MaistroOptions.constructFromObject(data['options']);
    }
    return obj;
  }
}

/**
 * The NTL script to evaluate.  Include either this or agent - not both
 * @member {String} ntl
 * @default ''
 */
MaistroBody.prototype.ntl = '';

/**
 * The agent to use. Include either this or NTL
 * @member {String} agent
 * @default ''
 */
MaistroBody.prototype.agent = '';

/**
 * An array of parameters to use in evaluation of the NTL
 * @member {Array.<module:model/SeekStreamParams>} params
 */
MaistroBody.prototype.params = undefined;

/**
 * @member {module:model/MaistroOptions} options
 */
MaistroBody.prototype.options = undefined;

