/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The PiiBody model module.
 * @module model/PiiBody
 * @version 1.0.1
 */
export default class PiiBody {
  /**
   * Constructs a new <code>PiiBody</code>.
   * @alias module:model/PiiBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PiiBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PiiBody} obj Optional instance to populate.
   * @return {module:model/PiiBody} The populated <code>PiiBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PiiBody();
      if (data.hasOwnProperty('text'))
        obj.text = ApiClient.convertToType(data['text'], 'String');
    }
    return obj;
  }
}

/**
 * The user utterance to check for PII
 * @member {String} text
 * @default ''
 */
PiiBody.prototype.text = '';

