/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The RateBody model module.
 * @module model/RateBody
 * @version 1.0.1
 */
export default class RateBody {
  /**
   * Constructs a new <code>RateBody</code>.
   * @alias module:model/RateBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RateBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RateBody} obj Optional instance to populate.
   * @return {module:model/RateBody} The populated <code>RateBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RateBody();
      if (data.hasOwnProperty('answerId'))
        obj.answerId = ApiClient.convertToType(data['answerId'], 'Number');
      if (data.hasOwnProperty('score'))
        obj.score = ApiClient.convertToType(data['score'], 'Number');
      if (data.hasOwnProperty('feedback'))
        obj.feedback = ApiClient.convertToType(data['feedback'], 'String');
    }
    return obj;
  }
}

/**
 * The answer id
 * @member {Number} answerId
 */
RateBody.prototype.answerId = undefined;

/**
 * The rating score. An integer, 0-5. 0 is worst, 5 is best.  For Thumbs up / Thumbs down send 0 or 5
 * @member {Number} score
 */
RateBody.prototype.score = undefined;

/**
 * text feedback on the answer
 * @member {String} feedback
 */
RateBody.prototype.feedback = undefined;

