/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ScoreBody model module.
 * @module model/ScoreBody
 * @version 1.0.1
 */
export default class ScoreBody {
  /**
   * Constructs a new <code>ScoreBody</code>.
   * @alias module:model/ScoreBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ScoreBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ScoreBody} obj Optional instance to populate.
   * @return {module:model/ScoreBody} The populated <code>ScoreBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ScoreBody();
      if (data.hasOwnProperty('text'))
        obj.text = ApiClient.convertToType(data['text'], 'String');
      if (data.hasOwnProperty('passages'))
        obj.passages = ApiClient.convertToType(data['passages'], ['String']);
    }
    return obj;
  }
}

/**
 * The text to score
 * @member {String} text
 * @default ''
 */
ScoreBody.prototype.text = '';

/**
 * The rating score. An integer, 0-5. 0 is worst, 5 is best.  For Thumbs up / Thumbs down send 0 or 5
 * @member {Array.<String>} passages
 */
ScoreBody.prototype.passages = undefined;

