/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The SeekStreamParams model module.
 * @module model/SeekStreamParams
 * @version 1.0.1
 */
export default class SeekStreamParams {
  /**
   * Constructs a new <code>SeekStreamParams</code>.
   * @alias module:model/SeekStreamParams
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SeekStreamParams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SeekStreamParams} obj Optional instance to populate.
   * @return {module:model/SeekStreamParams} The populated <code>SeekStreamParams</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SeekStreamParams();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
    }
    return obj;
  }
}

/**
 * The parameter name
 * @member {String} name
 * @default ''
 */
SeekStreamParams.prototype.name = '';

/**
 * The parameter value
 * @member {String} value
 * @default ''
 */
SeekStreamParams.prototype.value = '';

