/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import SeekStreamUserSessionMetadata from './SeekStreamUserSessionMetadata';
import SeekStreamUserSessionSystem from './SeekStreamUserSessionSystem';

/**
 * The SeekStreamUserSession model module.
 * @module model/SeekStreamUserSession
 * @version 1.0.1
 */
export default class SeekStreamUserSession {
  /**
   * Constructs a new <code>SeekStreamUserSession</code>.
   * Context tracking object. You must set at least one of user_id or session_id to enable context keeping.
   * @alias module:model/SeekStreamUserSession
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SeekStreamUserSession</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SeekStreamUserSession} obj Optional instance to populate.
   * @return {module:model/SeekStreamUserSession} The populated <code>SeekStreamUserSession</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SeekStreamUserSession();
      if (data.hasOwnProperty('metadata'))
        obj.metadata = SeekStreamUserSessionMetadata.constructFromObject(data['metadata']);
      if (data.hasOwnProperty('system'))
        obj.system = SeekStreamUserSessionSystem.constructFromObject(data['system']);
    }
    return obj;
  }
}

/**
 * @member {module:model/SeekStreamUserSessionMetadata} metadata
 */
SeekStreamUserSession.prototype.metadata = undefined;

/**
 * @member {module:model/SeekStreamUserSessionSystem} system
 */
SeekStreamUserSession.prototype.system = undefined;

