/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The SeekStreamOptionsPersonalize model module.
 * @module model/SeekStreamOptionsPersonalize
 * @version 1.0.1
 */
export default class SeekStreamOptionsPersonalize {
  /**
   * Constructs a new <code>SeekStreamOptionsPersonalize</code>.
   * An object that allows NeuralSeek to tailor a response for a specific user
   * @alias module:model/SeekStreamOptionsPersonalize
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SeekStreamOptionsPersonalize</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SeekStreamOptionsPersonalize} obj Optional instance to populate.
   * @return {module:model/SeekStreamOptionsPersonalize} The populated <code>SeekStreamOptionsPersonalize</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SeekStreamOptionsPersonalize();
      if (data.hasOwnProperty('preferredName'))
        obj.preferredName = ApiClient.convertToType(data['preferredName'], 'String');
      if (data.hasOwnProperty('noWelcome'))
        obj.noWelcome = ApiClient.convertToType(data['noWelcome'], 'String');
      if (data.hasOwnProperty('forceFirstPerson'))
        obj.forceFirstPerson = ApiClient.convertToType(data['forceFirstPerson'], 'String');
      if (data.hasOwnProperty('products'))
        obj.products = ApiClient.convertToType(data['products'], ['String']);
      if (data.hasOwnProperty('additionalDetails'))
        obj.additionalDetails = ApiClient.convertToType(data['additionalDetails'], 'String');
    }
    return obj;
  }
}

/**
 * The name the user should be referred to by
 * @member {String} preferredName
 * @default ''
 */
SeekStreamOptionsPersonalize.prototype.preferredName = '';

/**
 * The user has already been welcomed, do not re-welcome.  Valid value is 'true' or 'false'.  Default value is 'false'.
 * @member {String} noWelcome
 * @default ''
 */
SeekStreamOptionsPersonalize.prototype.noWelcome = '';

/**
 * Use a first-person speaking style, even if no preferredName is set.  Valid value is 'true' or 'false'.  Default value is 'false'.
 * @member {String} forceFirstPerson
 * @default ''
 */
SeekStreamOptionsPersonalize.prototype.forceFirstPerson = '';

/**
 * An array of products this customer currently consumes from your company
 * @member {Array.<String>} products
 */
SeekStreamOptionsPersonalize.prototype.products = undefined;

/**
 * Additional details to pass to language generation
 * @member {String} additionalDetails
 * @default ''
 */
SeekStreamOptionsPersonalize.prototype.additionalDetails = '';

