/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import SeekResponsePassages from './SeekResponsePassages';
import SeekResponseVariablesExpanded from './SeekResponseVariablesExpanded';

/**
 * The SeekResponse model module.
 * @module model/SeekResponse
 * @version 1.0.1
 */
export default class SeekResponse {
  /**
   * Constructs a new <code>SeekResponse</code>.
   * @alias module:model/SeekResponse
   * @class
   * @param answer {String} The generated answer
   * @param score {Number} The final confidence score of the answer (0-100)
   */
  constructor(answer, score) {
    this.answer = answer;
    this.score = score;
  }

  /**
   * Constructs a <code>SeekResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SeekResponse} obj Optional instance to populate.
   * @return {module:model/SeekResponse} The populated <code>SeekResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SeekResponse();
      if (data.hasOwnProperty('answer'))
        obj.answer = ApiClient.convertToType(data['answer'], 'String');
      if (data.hasOwnProperty('ufa'))
        obj.ufa = ApiClient.convertToType(data['ufa'], 'String');
      if (data.hasOwnProperty('answerId'))
        obj.answerId = ApiClient.convertToType(data['answerId'], 'String');
      if (data.hasOwnProperty('thumbs'))
        obj.thumbs = ApiClient.convertToType(data['thumbs'], 'String');
      if (data.hasOwnProperty('thumbsSVG'))
        obj.thumbsSVG = ApiClient.convertToType(data['thumbsSVG'], 'String');
      if (data.hasOwnProperty('intent'))
        obj.intent = ApiClient.convertToType(data['intent'], 'String');
      if (data.hasOwnProperty('category'))
        obj.category = ApiClient.convertToType(data['category'], 'Number');
      if (data.hasOwnProperty('categoryName'))
        obj.categoryName = ApiClient.convertToType(data['categoryName'], 'String');
      if (data.hasOwnProperty('score'))
        obj.score = ApiClient.convertToType(data['score'], 'Number');
      if (data.hasOwnProperty('KBscore'))
        obj.kBscore = ApiClient.convertToType(data['KBscore'], 'Number');
      if (data.hasOwnProperty('semanticAnalysis'))
        obj.semanticAnalysis = ApiClient.convertToType(data['semanticAnalysis'], 'String');
      if (data.hasOwnProperty('cachedResult'))
        obj.cachedResult = ApiClient.convertToType(data['cachedResult'], 'String');
      if (data.hasOwnProperty('langCode'))
        obj.langCode = ApiClient.convertToType(data['langCode'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('document'))
        obj.document = ApiClient.convertToType(data['document'], 'String');
      if (data.hasOwnProperty('time'))
        obj.time = ApiClient.convertToType(data['time'], 'Number');
      if (data.hasOwnProperty('kbTime'))
        obj.kbTime = ApiClient.convertToType(data['kbTime'], 'Number');
      if (data.hasOwnProperty('protectTime'))
        obj.protectTime = ApiClient.convertToType(data['protectTime'], 'Number');
      if (data.hasOwnProperty('categorySelectionTime'))
        obj.categorySelectionTime = ApiClient.convertToType(data['categorySelectionTime'], 'Number');
      if (data.hasOwnProperty('promptInjection'))
        obj.promptInjection = ApiClient.convertToType(data['promptInjection'], 'Number');
      if (data.hasOwnProperty('sourceResultsFormatted'))
        obj.sourceResultsFormatted = ApiClient.convertToType(data['sourceResultsFormatted'], 'String');
      if (data.hasOwnProperty('passages'))
        obj.passages = ApiClient.convertToType(data['passages'], [SeekResponsePassages]);
      if (data.hasOwnProperty('kbCoverage'))
        obj.kbCoverage = ApiClient.convertToType(data['kbCoverage'], 'Number');
      if (data.hasOwnProperty('sentiment'))
        obj.sentiment = ApiClient.convertToType(data['sentiment'], 'Number');
      if (data.hasOwnProperty('semanticScore'))
        obj.semanticScore = ApiClient.convertToType(data['semanticScore'], 'Number');
      if (data.hasOwnProperty('variables'))
        obj.variables = ApiClient.convertToType(data['variables'], Object);
      if (data.hasOwnProperty('variablesExpanded'))
        obj.variablesExpanded = ApiClient.convertToType(data['variablesExpanded'], [SeekResponseVariablesExpanded]);
    }
    return obj;
  }
}

/**
 * The generated answer
 * @member {String} answer
 * @default ''
 */
SeekResponse.prototype.answer = '';

/**
 * The raw answer from the LLM before guardrails are applied.
 * @member {String} ufa
 * @default ''
 */
SeekResponse.prototype.ufa = '';

/**
 * The id of the answer. Use this to refer to it from other endpoints, such as the Rating endpoint
 * @member {String} answerId
 * @default ''
 */
SeekResponse.prototype.answerId = '';

/**
 * The URL of a rating HTML page with an SVG to embed with the answer to allow easy rating.
 * @member {String} thumbs
 * @default ''
 */
SeekResponse.prototype.thumbs = '';

/**
 * The URL of a rating SVG to display with the answer to allow easy rating.
 * @member {String} thumbsSVG
 * @default ''
 */
SeekResponse.prototype.thumbsSVG = '';

/**
 * The intent of the answer.
 * @member {String} intent
 * @default ''
 */
SeekResponse.prototype.intent = '';

/**
 * The category id of the answer.
 * @member {Number} category
 */
SeekResponse.prototype.category = undefined;

/**
 * The category name of the answer.
 * @member {String} categoryName
 * @default ''
 */
SeekResponse.prototype.categoryName = '';

/**
 * The final confidence score of the answer (0-100)
 * @member {Number} score
 */
SeekResponse.prototype.score = undefined;

/**
 * The KnowledgeBase confidence of the answer's source documentation  (0-100)
 * @member {Number} kBscore
 */
SeekResponse.prototype.kBscore = undefined;

/**
 * Semantic Analysis
 * @member {String} semanticAnalysis
 * @default ''
 */
SeekResponse.prototype.semanticAnalysis = '';

/**
 * If the result came from cache, will be set to the string 'true'
 * @member {String} cachedResult
 * @default ''
 */
SeekResponse.prototype.cachedResult = '';

/**
 * The language code of the answer. If you set the input language code to 'xx' to identify the language, this is useful to condition of the found language and response.
 * @member {String} langCode
 * @default ''
 */
SeekResponse.prototype.langCode = '';

/**
 * The top scoring URL (if available) used to train the answer. Set the field you want returned here in on the Configure tab. The field must contain a URL, or it will be ignored.
 * @member {String} url
 * @default ''
 */
SeekResponse.prototype.url = '';

/**
 * The top document (if available) used to train the answer. Set the field you want returned here in on the Configure tab
 * @member {String} document
 * @default ''
 */
SeekResponse.prototype.document = '';

/**
 * Total processing time in milliseconds
 * @member {Number} time
 */
SeekResponse.prototype.time = undefined;

/**
 * KnowledgeBase response time in milliseconds
 * @member {Number} kbTime
 */
SeekResponse.prototype.kbTime = undefined;

/**
 * PI time in milliseconds
 * @member {Number} protectTime
 */
SeekResponse.prototype.protectTime = undefined;

/**
 * Category Selection time in milliseconds
 * @member {Number} categorySelectionTime
 */
SeekResponse.prototype.categorySelectionTime = undefined;

/**
 * Prompt injection value
 * @member {Number} promptInjection
 */
SeekResponse.prototype.promptInjection = undefined;

/**
 * A listing of the passages used for answer summarization. This will only return if includeSourceResultsFormatted is set to true on the request
 * @member {String} sourceResultsFormatted
 * @default ''
 */
SeekResponse.prototype.sourceResultsFormatted = '';

/**
 * A listing of the passages used for answer summarization. This will only return if includeSourceResults is set to true on the request
 * @member {Array.<module:model/SeekResponsePassages>} passages
 */
SeekResponse.prototype.passages = undefined;

/**
 * KnowledgeBase coverage score. How much content was returned from the KnowledgeBase on the subject asked as compared to benchmarks. Low coverage is not necessarily indicitive of bad content.
 * @member {Number} kbCoverage
 */
SeekResponse.prototype.kbCoverage = undefined;

/**
 * Sentiment score
 * @member {Number} sentiment
 */
SeekResponse.prototype.sentiment = undefined;

/**
 * Semantic score (if enabled)
 * @member {Number} semanticScore
 */
SeekResponse.prototype.semanticScore = undefined;

/**
 * The returned variable.
 * @member {Object} variables
 */
SeekResponse.prototype.variables = undefined;

/**
 * The returned variable, in the format of the input params
 * @member {Array.<module:model/SeekResponseVariablesExpanded>} variablesExpanded
 */
SeekResponse.prototype.variablesExpanded = undefined;

