/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The SeekStreamOptionsLastTurn model module.
 * @module model/SeekStreamOptionsLastTurn
 * @version 1.0.1
 */
export default class SeekStreamOptionsLastTurn {
  /**
   * Constructs a new <code>SeekStreamOptionsLastTurn</code>.
   * @alias module:model/SeekStreamOptionsLastTurn
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SeekStreamOptionsLastTurn</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SeekStreamOptionsLastTurn} obj Optional instance to populate.
   * @return {module:model/SeekStreamOptionsLastTurn} The populated <code>SeekStreamOptionsLastTurn</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SeekStreamOptionsLastTurn();
      if (data.hasOwnProperty('input'))
        obj.input = ApiClient.convertToType(data['input'], 'String');
      if (data.hasOwnProperty('response'))
        obj.response = ApiClient.convertToType(data['response'], 'String');
    }
    return obj;
  }
}

/**
 * The user input
 * @member {String} input
 * @default ''
 */
SeekStreamOptionsLastTurn.prototype.input = '';

/**
 * The system response.  Text strings only here. 
 * @member {String} response
 * @default ''
 */
SeekStreamOptionsLastTurn.prototype.response = '';

