/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import SeekStreamOptionsLastTurn from './SeekStreamOptionsLastTurn';
import SeekStreamOptionsPersonalize from './SeekStreamOptionsPersonalize';

/**
 * The SeekStreamOptions model module.
 * @module model/SeekStreamOptions
 * @version 1.0.1
 */
export default class SeekStreamOptions {
  /**
   * Constructs a new <code>SeekStreamOptions</code>.
   * Optional object for runtime override of Seek options.
   * @alias module:model/SeekStreamOptions
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SeekStreamOptions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SeekStreamOptions} obj Optional instance to populate.
   * @return {module:model/SeekStreamOptions} The populated <code>SeekStreamOptions</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SeekStreamOptions();
      if (data.hasOwnProperty('personalize'))
        obj.personalize = SeekStreamOptionsPersonalize.constructFromObject(data['personalize']);
      if (data.hasOwnProperty('proposalID'))
        obj.proposalID = ApiClient.convertToType(data['proposalID'], 'String');
      if (data.hasOwnProperty('seekLLM'))
        obj.seekLLM = ApiClient.convertToType(data['seekLLM'], 'String');
      if (data.hasOwnProperty('language'))
        obj.language = ApiClient.convertToType(data['language'], 'String');
      if (data.hasOwnProperty('filter'))
        obj.filter = ApiClient.convertToType(data['filter'], 'String');
      if (data.hasOwnProperty('lastTurn'))
        obj.lastTurn = ApiClient.convertToType(data['lastTurn'], [SeekStreamOptionsLastTurn]);
      if (data.hasOwnProperty('promptEngineering'))
        obj.promptEngineering = ApiClient.convertToType(data['promptEngineering'], 'String');
      if (data.hasOwnProperty('promptEngineeringPhrase'))
        obj.promptEngineeringPhrase = ApiClient.convertToType(data['promptEngineeringPhrase'], 'String');
      if (data.hasOwnProperty('answerLength'))
        obj.answerLength = ApiClient.convertToType(data['answerLength'], 'Number');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('stump'))
        obj.stump = ApiClient.convertToType(data['stump'], 'String');
      if (data.hasOwnProperty('includeSourceResults'))
        obj.includeSourceResults = ApiClient.convertToType(data['includeSourceResults'], 'Boolean');
      if (data.hasOwnProperty('includeHighlights'))
        obj.includeHighlights = ApiClient.convertToType(data['includeHighlights'], 'Boolean');
      if (data.hasOwnProperty('includeSourceResultsFormatted'))
        obj.includeSourceResultsFormatted = ApiClient.convertToType(data['includeSourceResultsFormatted'], 'Boolean');
      if (data.hasOwnProperty('sourceResultsNumber'))
        obj.sourceResultsNumber = ApiClient.convertToType(data['sourceResultsNumber'], 'Number');
      if (data.hasOwnProperty('sourceResultsSummaryLength'))
        obj.sourceResultsSummaryLength = ApiClient.convertToType(data['sourceResultsSummaryLength'], 'Number');
      if (data.hasOwnProperty('returnVariables'))
        obj.returnVariables = ApiClient.convertToType(data['returnVariables'], 'Boolean');
      if (data.hasOwnProperty('returnVariablesExpanded'))
        obj.returnVariablesExpanded = ApiClient.convertToType(data['returnVariablesExpanded'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {module:model/SeekStreamOptionsPersonalize} personalize
 */
SeekStreamOptions.prototype.personalize = undefined;

/**
 * Override all settings by passing a NeuralSeek Proposal ID.
 * @member {String} proposalID
 * @default ''
 */
SeekStreamOptions.prototype.proposalID = '';

/**
 * Override the LLM load balancer and force seek to use a specific LLM.  Input the LLM code here.  You must have a valid model card set up on the configure tab for the code you input.
 * @member {String} seekLLM
 * @default ''
 */
SeekStreamOptions.prototype.seekLLM = '';

/**
 * Valid values are: en, es, de, it, fr, ja, ar
 * @member {String} language
 * @default ''
 */
SeekStreamOptions.prototype.language = '';

/**
 * Text to use as a filter against the filter field set in the KnowledgeBase configuration. Use commas to separate multiple strings for an 'or' filter. You can use the filter to isolate a certain subset of documents in the knowledgebase.
 * @member {String} filter
 * @default ''
 */
SeekStreamOptions.prototype.filter = '';

/**
 * lastTurn is a flexible object. It is backwards compatible with the original single turn object, as well as compatible with the Watson Assistant session history format.
 * @member {Array.<module:model/SeekStreamOptionsLastTurn>} lastTurn
 */
SeekStreamOptions.prototype.lastTurn = undefined;

/**
 * Enable Prompt engineering.  Valid values are the strings 'true' and 'false'
 * @member {String} promptEngineering
 * @default ''
 */
SeekStreamOptions.prototype.promptEngineering = '';

/**
 * Prepend a phrase to cleansed user input. Must enable Prompt Engineering inside the NeuralSeek \"Configure\" page
 * @member {String} promptEngineeringPhrase
 * @default ''
 */
SeekStreamOptions.prototype.promptEngineeringPhrase = '';

/**
 * The verbosity of the answer. A whole number 1-4
 * @member {Number} answerLength
 */
SeekStreamOptions.prototype.answerLength = undefined;

/**
 * URL of the current page when using with a web-based Virtual Agent
 * @member {String} url
 * @default ''
 */
SeekStreamOptions.prototype.url = '';

/**
 * Stump Speech text. Fallback for when all else fails.
 * @member {String} stump
 * @default ''
 */
SeekStreamOptions.prototype.stump = '';

/**
 * Include generation source results. Defaults to false.
 * @member {Boolean} includeSourceResults
 * @default false
 */
SeekStreamOptions.prototype.includeSourceResults = false;

/**
 * Include highlights from source results. Defaults to false.
 * @member {Boolean} includeHighlights
 * @default false
 */
SeekStreamOptions.prototype.includeHighlights = false;

/**
 * Include generation source results, and output them into a formatted string.  Defaults to false.
 * @member {Boolean} includeSourceResultsFormatted
 * @default false
 */
SeekStreamOptions.prototype.includeSourceResultsFormatted = false;

/**
 * When including source results, how many to include.'
 * @member {Number} sourceResultsNumber
 * @default 3
 */
SeekStreamOptions.prototype.sourceResultsNumber = 3;

/**
 * When including source results, how long of a summary to include.'
 * @member {Number} sourceResultsSummaryLength
 * @default 100
 */
SeekStreamOptions.prototype.sourceResultsSummaryLength = 100;

/**
 * Return the final state of all variables in a dense object
 * @member {Boolean} returnVariables
 * @default false
 */
SeekStreamOptions.prototype.returnVariables = false;

/**
 * Return the final state of all variables in the same format as the input params
 * @member {Boolean} returnVariablesExpanded
 * @default false
 */
SeekStreamOptions.prototype.returnVariablesExpanded = false;

