/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The SeekStreamUserSessionMetadata model module.
 * @module model/SeekStreamUserSessionMetadata
 * @version 1.0.1
 */
export default class SeekStreamUserSessionMetadata {
  /**
   * Constructs a new <code>SeekStreamUserSessionMetadata</code>.
   * @alias module:model/SeekStreamUserSessionMetadata
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SeekStreamUserSessionMetadata</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SeekStreamUserSessionMetadata} obj Optional instance to populate.
   * @return {module:model/SeekStreamUserSessionMetadata} The populated <code>SeekStreamUserSessionMetadata</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SeekStreamUserSessionMetadata();
      if (data.hasOwnProperty('user_id'))
        obj.userId = ApiClient.convertToType(data['user_id'], 'String');
    }
    return obj;
  }
}

/**
 * A unique user identifier.
 * @member {String} userId
 * @default ''
 */
SeekStreamUserSessionMetadata.prototype.userId = '';

