/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The SeekStreamUserSessionSystem model module.
 * @module model/SeekStreamUserSessionSystem
 * @version 1.0.1
 */
export default class SeekStreamUserSessionSystem {
  /**
   * Constructs a new <code>SeekStreamUserSessionSystem</code>.
   * @alias module:model/SeekStreamUserSessionSystem
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SeekStreamUserSessionSystem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SeekStreamUserSessionSystem} obj Optional instance to populate.
   * @return {module:model/SeekStreamUserSessionSystem} The populated <code>SeekStreamUserSessionSystem</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SeekStreamUserSessionSystem();
      if (data.hasOwnProperty('session_id'))
        obj.sessionId = ApiClient.convertToType(data['session_id'], 'String');
    }
    return obj;
  }
}

/**
 * A session identifier for the defined user.
 * @member {String} sessionId
 * @default ''
 */
SeekStreamUserSessionSystem.prototype.sessionId = '';

