/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import SeekStreamOptions from './SeekStreamOptions';
import SeekStreamParams from './SeekStreamParams';
import SeekStreamUserSession from './SeekStreamUserSession';

/**
 * The SeekStreamBody model module.
 * @module model/SeekStreamBody
 * @version 1.0.1
 */
export default class SeekStreamBody {
  /**
   * Constructs a new <code>SeekStreamBody</code>.
   * @alias module:model/SeekStreamBody
   * @class
   * @param question {String} The user's question for NeuralSeek
   */
  constructor(question) {
    this.question = question;
  }

  /**
   * Constructs a <code>SeekStreamBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SeekStreamBody} obj Optional instance to populate.
   * @return {module:model/SeekStreamBody} The populated <code>SeekStreamBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SeekStreamBody();
      if (data.hasOwnProperty('question'))
        obj.question = ApiClient.convertToType(data['question'], 'String');
      if (data.hasOwnProperty('user_session'))
        obj.userSession = SeekStreamUserSession.constructFromObject(data['user_session']);
      if (data.hasOwnProperty('params'))
        obj.params = ApiClient.convertToType(data['params'], [SeekStreamParams]);
      if (data.hasOwnProperty('options'))
        obj.options = SeekStreamOptions.constructFromObject(data['options']);
    }
    return obj;
  }
}

/**
 * The user's question for NeuralSeek
 * @member {String} question
 * @default ''
 */
SeekStreamBody.prototype.question = '';

/**
 * @member {module:model/SeekStreamUserSession} userSession
 */
SeekStreamBody.prototype.userSession = undefined;

/**
 * An array of parameters to use in evaluation of the seek when calling mAIstro during a seek.
 * @member {Array.<module:model/SeekStreamParams>} params
 */
SeekStreamBody.prototype.params = undefined;

/**
 * @member {module:model/SeekStreamOptions} options
 */
SeekStreamBody.prototype.options = undefined;

