/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The SeekResponsePassages model module.
 * @module model/SeekResponsePassages
 * @version 1.0.1
 */
export default class SeekResponsePassages {
  /**
   * Constructs a new <code>SeekResponsePassages</code>.
   * @alias module:model/SeekResponsePassages
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SeekResponsePassages</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SeekResponsePassages} obj Optional instance to populate.
   * @return {module:model/SeekResponsePassages} The populated <code>SeekResponsePassages</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SeekResponsePassages();
      if (data.hasOwnProperty('passage'))
        obj.passage = ApiClient.convertToType(data['passage'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('score'))
        obj.score = ApiClient.convertToType(data['score'], 'Number');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('document'))
        obj.document = ApiClient.convertToType(data['document'], 'String');
      if (data.hasOwnProperty('train'))
        obj.train = ApiClient.convertToType(data['train'], 'String');
    }
    return obj;
  }
}

/**
 * The passage text, summarized to the length set by sourceResultsSummaryLength
 * @member {String} passage
 * @default ''
 */
SeekResponsePassages.prototype.passage = '';

/**
 * The id of the source document in the KB.
 * @member {String} id
 * @default ''
 */
SeekResponsePassages.prototype.id = '';

/**
 * The score of the passage.
 * @member {Number} score
 */
SeekResponsePassages.prototype.score = undefined;

/**
 * The URL (if available) of the source document.
 * @member {String} url
 * @default ''
 */
SeekResponsePassages.prototype.url = '';

/**
 * The name of the source document.
 * @member {String} document
 * @default ''
 */
SeekResponsePassages.prototype.document = '';

/**
 * The training token for the document. Use this when calling the /train endpoint.
 * @member {String} train
 * @default ''
 */
SeekResponsePassages.prototype.train = '';

