/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The TestBody1 model module.
 * @module model/TestBody1
 * @version 1.0.1
 */
export default class TestBody1 {
  /**
   * Constructs a new <code>TestBody1</code>.
   * @alias module:model/TestBody1
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TestBody1</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TestBody1} obj Optional instance to populate.
   * @return {module:model/TestBody1} The populated <code>TestBody1</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TestBody1();
      if (data.hasOwnProperty('proposalID'))
        obj.proposalID = ApiClient.convertToType(data['proposalID'], 'String');
    }
    return obj;
  }
}

/**
 * An optional Proposal ID to use for the test
 * @member {String} proposalID
 * @default ''
 */
TestBody1.prototype.proposalID = '';

