/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The TrainBody model module.
 * @module model/TrainBody
 * @version 1.0.1
 */
export default class TrainBody {
  /**
   * Constructs a new <code>TrainBody</code>.
   * @alias module:model/TrainBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TrainBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TrainBody} obj Optional instance to populate.
   * @return {module:model/TrainBody} The populated <code>TrainBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TrainBody();
      if (data.hasOwnProperty('train'))
        obj.train = ApiClient.convertToType(data['train'], 'String');
      if (data.hasOwnProperty('score'))
        obj.score = ApiClient.convertToType(data['score'], 'Number');
    }
    return obj;
  }
}

/**
 * The training token. Get this from passages/train
 * @member {String} train
 * @default ''
 */
TrainBody.prototype.train = '';

/**
 * The relevancy score. An integer, 0-100
 * @member {Number} score
 */
TrainBody.prototype.score = undefined;

