/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The TranslateGlossaryBody model module.
 * @module model/TranslateGlossaryBody
 * @version 1.0.1
 */
export default class TranslateGlossaryBody {
  /**
   * Constructs a new <code>TranslateGlossaryBody</code>.
   * @alias module:model/TranslateGlossaryBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TranslateGlossaryBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TranslateGlossaryBody} obj Optional instance to populate.
   * @return {module:model/TranslateGlossaryBody} The populated <code>TranslateGlossaryBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TranslateGlossaryBody();
      if (data.hasOwnProperty('file'))
        obj.file = ApiClient.convertToType(data['file'], 'Blob');
    }
    return obj;
  }
}

/**
 * @member {Blob} file
 */
TranslateGlossaryBody.prototype.file = undefined;

