/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The TranslateBody model module.
 * @module model/TranslateBody
 * @version 1.0.1
 */
export default class TranslateBody {
  /**
   * Constructs a new <code>TranslateBody</code>.
   * @alias module:model/TranslateBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TranslateBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TranslateBody} obj Optional instance to populate.
   * @return {module:model/TranslateBody} The populated <code>TranslateBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TranslateBody();
      if (data.hasOwnProperty('text'))
        obj.text = ApiClient.convertToType(data['text'], ['String']);
      if (data.hasOwnProperty('model_id'))
        obj.modelId = ApiClient.convertToType(data['model_id'], 'String');
      if (data.hasOwnProperty('target'))
        obj.target = ApiClient.convertToType(data['target'], 'String');
      if (data.hasOwnProperty('llmId'))
        obj.llmId = ApiClient.convertToType(data['llmId'], 'String');
      if (data.hasOwnProperty('maxChunk'))
        obj.maxChunk = ApiClient.convertToType(data['maxChunk'], 'Number');
      if (data.hasOwnProperty('additionalInstructions'))
        obj.additionalInstructions = ApiClient.convertToType(data['additionalInstructions'], 'String');
    }
    return obj;
  }
}

/**
 * An array of input text to be translated
 * @member {Array.<String>} text
 */
TranslateBody.prototype.text = undefined;

/**
 * Convienence input for legacy connections. Define a traget language by setting a source to target relationship using 2-digit language codes, for example en-es to translate into spanish.  The source language is ignored. Either this or the target parameter is required.
 * @member {String} modelId
 * @default ''
 */
TranslateBody.prototype.modelId = '';

/**
 * The 2-digit language code for the target language.  Either this or the model_id parameter is required.
 * @member {String} target
 * @default ''
 */
TranslateBody.prototype.target = '';

/**
 * Optional - Pass an llm card id to override the LLM used for translation
 * @member {String} llmId
 * @default ''
 */
TranslateBody.prototype.llmId = '';

/**
 * Optional - Pass a maximum translation chunk token size. This can help speed up translations in the 200-2000 word range when using slower LLM's.  Use a setting between 200 and 500 in these scenarios. Setting 0 or omitting this parameter unsets it.
 * @member {Number} maxChunk
 * @default 0
 */
TranslateBody.prototype.maxChunk = 0;

/**
 * Optional - Additional prompting to be passed to the LLM. Do not casusally use this field, you will break things.
 * @member {String} additionalInstructions
 * @default ''
 */
TranslateBody.prototype.additionalInstructions = '';

