/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The TranslateGlossaryBody1 model module.
 * @module model/TranslateGlossaryBody1
 * @version 1.0.1
 */
export default class TranslateGlossaryBody1 {
  /**
   * Constructs a new <code>TranslateGlossaryBody1</code>.
   * @alias module:model/TranslateGlossaryBody1
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TranslateGlossaryBody1</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TranslateGlossaryBody1} obj Optional instance to populate.
   * @return {module:model/TranslateGlossaryBody1} The populated <code>TranslateGlossaryBody1</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TranslateGlossaryBody1();
      if (data.hasOwnProperty('sentences'))
        obj.sentences = ApiClient.convertToType(data['sentences'], [[Object]]);
    }
    return obj;
  }
}

/**
 * Instead of a file upload you may pass sentence mappings
 * @member {Array.<Array.<Object>>} sentences
 */
TranslateGlossaryBody1.prototype.sentences = undefined;

