/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import CategorizeBody from '../model/CategorizeBody';
import InlineResponse2005 from '../model/InlineResponse2005';

/**
* Categorize service.
* @module api/CategorizeApi
* @version 1.0.1
*/
export default class CategorizeApi {

    /**
    * Constructs a new CategorizeApi. 
    * @alias module:api/CategorizeApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the categorize operation.
     * @callback moduleapi/CategorizeApi~categorizeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2005{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Categorize text into an Intent &amp; Category
     * Categorize text into an Intent &amp; Category
     * @param {module:model/CategorizeBody} body The request object.
     * @param {module:api/CategorizeApi~categorizeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    categorize(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling categorize");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['apiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InlineResponse2005;

      return this.apiClient.callApi(
        '/categorize', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}