/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import InlineResponse20010 from '../model/InlineResponse20010';
import PiiBody from '../model/PiiBody';
import ScoreBody from '../model/ScoreBody';

/**
* Guardrails service.
* @module api/GuardrailsApi
* @version 1.0.1
*/
export default class GuardrailsApi {

    /**
    * Constructs a new GuardrailsApi. 
    * @alias module:api/GuardrailsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the pii operation.
     * @callback moduleapi/GuardrailsApi~piiCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/InlineResponse20010>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find PII in a user utterance
     * Find PII in a user utterance
     * @param {module:model/PiiBody} body The request object.
     * @param {module:api/GuardrailsApi~piiCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    pii(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling pii");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['apiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [InlineResponse20010];

      return this.apiClient.callApi(
        '/pii', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the score operation.
     * @callback moduleapi/GuardrailsApi~scoreCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Run the Semantic Scoring model on text against an array of passages
     * Run the Semantic Scoring model on text against an array of passages
     * @param {module:model/ScoreBody} body The request object.  Must include the question and a context.
     * @param {module:api/GuardrailsApi~scoreCallback} callback The callback function, accepting three arguments: error, data, response
     */
    score(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling score");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['apiKey'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/score', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}