/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import InlineResponse200 from '../model/InlineResponse200';
import Seek from '../model/Seek';
import SeekResponse from '../model/SeekResponse';
import SeekStreamBody from '../model/SeekStreamBody';

/**
* Seek service.
* @module api/SeekApi
* @version 1.0.1
*/
export default class SeekApi {

    /**
    * Constructs a new SeekApi. 
    * @alias module:api/SeekApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the seek operation.
     * @callback moduleapi/SeekApi~seekCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SeekResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Seek an answer from NeuralSeek
     * This endpoint takes an input object with a user question, context and options and returns a response object
     * @param {module:model/Seek} body The request object.  Must include the question and a context.
     * @param {module:api/SeekApi~seekCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    seek(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling seek");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['apiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SeekResponse;

      return this.apiClient.callApi(
        '/seek', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the seekStream operation.
     * @callback moduleapi/SeekApi~seekStreamCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse200{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Stream a Seek an answer from NeuralSeek
     * This endpoint takes an input object with a user question, context and options and returns a response object
     * @param {module:model/SeekStreamBody} body The request object.  Must include the question and a context.
     * @param {module:api/SeekApi~seekStreamCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    seekStream(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling seekStream");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['apiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['text/event-stream'];
      let returnType = InlineResponse200;

      return this.apiClient.callApi(
        '/seek_stream', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}