/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import IdentifysingleBody from '../model/IdentifysingleBody';
import InlineResponse2007 from '../model/InlineResponse2007';
import InlineResponse2008 from '../model/InlineResponse2008';
import InlineResponse2009 from '../model/InlineResponse2009';
import TranslateBody from '../model/TranslateBody';
import TranslateGlossaryBody1 from '../model/TranslateGlossaryBody1';

/**
* Translate service.
* @module api/TranslateApi
* @version 1.0.1
*/
export default class TranslateApi {

    /**
    * Constructs a new TranslateApi. 
    * @alias module:api/TranslateApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the deleteTranslateGlossary operation.
     * @callback moduleapi/TranslateApi~deleteTranslateGlossaryCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete the custom translations
     * Delete the custom translations
     * @param {module:api/TranslateApi~deleteTranslateGlossaryCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteTranslateGlossary(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['apiKey'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/translateGlossary', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the identifyLanguage operation.
     * @callback moduleapi/TranslateApi~identifyLanguageCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/InlineResponse2008>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Identify the source language
     * Identify the source language
     * @param {String} body The request object.
     * @param {module:api/TranslateApi~identifyLanguageCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    identifyLanguage(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling identifyLanguage");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['apiKey'];
      let contentTypes = ['text/plain'];
      let accepts = ['application/json'];
      let returnType = [InlineResponse2008];

      return this.apiClient.callApi(
        '/identify', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the identifyLanguageJSON operation.
     * @callback moduleapi/TranslateApi~identifyLanguageJSONCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2009{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Identify the source language (JSON)
     * Identify the source language (JSON)
     * @param {module:model/IdentifysingleBody} body The request object.
     * @param {module:api/TranslateApi~identifyLanguageJSONCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    identifyLanguageJSON(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling identifyLanguageJSON");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['apiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InlineResponse2009;

      return this.apiClient.callApi(
        '/identify-single', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the translate operation.
     * @callback moduleapi/TranslateApi~translateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2007{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Translate text into a desired language
     * Translate text into a desired language
     * @param {module:model/TranslateBody} body The request object.
     * @param {module:api/TranslateApi~translateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    translate(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling translate");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['apiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InlineResponse2007;

      return this.apiClient.callApi(
        '/translate', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the translateGlossary operation.
     * @callback moduleapi/TranslateApi~translateGlossaryCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add custom translations
     * Add custom translations
     * @param {Blob} file 
     * @param {module:model/TranslateGlossaryBody1} body This endpoint will accept either a file upload (TMX or JSON), or a direct JSON payload following IBM&#x27;s JSON file format https://cloud.ibm.com/docs/language-translator?topic&#x3D;language-translator-customizing#json.  Only one file may be saved. Subsequent files will overwrite.
     * @param {module:api/TranslateApi~translateGlossaryCallback} callback The callback function, accepting three arguments: error, data, response
     */
    translateGlossary(file, body, callback) {
      
      let postBody = body;
      // verify the required parameter 'file' is set
      if (file === undefined || file === null) {
        throw new Error("Missing the required parameter 'file' when calling translateGlossary");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling translateGlossary");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        'file': file
      };

      let authNames = ['apiKey'];
      let contentTypes = ['multipart/form-data', 'application/json'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/translateGlossary', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}