/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";

/**
* UserData service.
* @module api/UserDataApi
* @version 1.0.1
*/
export default class UserDataApi {

    /**
    * Constructs a new UserDataApi. 
    * @alias module:api/UserDataApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the deleteUserData operation.
     * @callback moduleapi/UserDataApi~deleteUserDataCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete all user data
     * This endpoint deletes all user data
     * @param {Object} opts Optional parameters
     * @param {Array.<String>} opts.intent The intents to delete. If left blank all intents will be deleted.
     * @param {module:api/UserDataApi~deleteUserDataCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteUserData(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'intent': this.apiClient.buildCollectionParam(opts['intent'], 'multi')
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['apiKey'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/user_data', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}