/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NeuralSeek);
  }
}(this, function(expect, NeuralSeek) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ExtractBody', function() {
      beforeEach(function() {
        instance = new NeuralSeek.ExtractBody();
      });

      it('should create an instance of ExtractBody', function() {
        // TODO: update the code to test ExtractBody
        expect(instance).to.be.a(NeuralSeek.ExtractBody);
      });

      it('should have the property text (base name: "text")', function() {
        // TODO: update the code to test the property text
        expect(instance).to.have.property('text');
        // expect(instance.text).to.be(expectedValueLiteral);
      });

      it('should have the property language (base name: "language")', function() {
        // TODO: update the code to test the property language
        expect(instance).to.have.property('language');
        // expect(instance.language).to.be(expectedValueLiteral);
      });

      it('should have the property entities (base name: "entities")', function() {
        // TODO: update the code to test the property entities
        expect(instance).to.have.property('entities');
        // expect(instance.entities).to.be(expectedValueLiteral);
      });

      it('should have the property slots (base name: "slots")', function() {
        // TODO: update the code to test the property slots
        expect(instance).to.have.property('slots');
        // expect(instance.slots).to.be(expectedValueLiteral);
      });

      it('should have the property confirmSlots (base name: "confirmSlots")', function() {
        // TODO: update the code to test the property confirmSlots
        expect(instance).to.have.property('confirmSlots');
        // expect(instance.confirmSlots).to.be(expectedValueLiteral);
      });

      it('should have the property confirmEverySlot (base name: "confirmEverySlot")', function() {
        // TODO: update the code to test the property confirmEverySlot
        expect(instance).to.have.property('confirmEverySlot');
        // expect(instance.confirmEverySlot).to.be(expectedValueLiteral);
      });

    });
  });

}));
