/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NeuralSeek);
  }
}(this, function(expect, NeuralSeek) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse2002Render', function() {
      beforeEach(function() {
        instance = new NeuralSeek.InlineResponse2002Render();
      });

      it('should create an instance of InlineResponse2002Render', function() {
        // TODO: update the code to test InlineResponse2002Render
        expect(instance).to.be.a(NeuralSeek.InlineResponse2002Render);
      });

      it('should have the property node (base name: "node")', function() {
        // TODO: update the code to test the property node
        expect(instance).to.have.property('node');
        // expect(instance.node).to.be(expectedValueLiteral);
      });

      it('should have the property vars (base name: "vars")', function() {
        // TODO: update the code to test the property vars
        expect(instance).to.have.property('vars');
        // expect(instance.vars).to.be(expectedValueLiteral);
      });

      it('should have the property out (base name: "out")', function() {
        // TODO: update the code to test the property out
        expect(instance).to.have.property('out');
        // expect(instance.out).to.be(expectedValueLiteral);
      });

      it('should have the property chained (base name: "chained")', function() {
        // TODO: update the code to test the property chained
        expect(instance).to.have.property('chained');
        // expect(instance.chained).to.be(expectedValueLiteral);
      });

    });
  });

}));
