/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NeuralSeek);
  }
}(this, function(expect, NeuralSeek) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse2007', function() {
      beforeEach(function() {
        instance = new NeuralSeek.InlineResponse2007();
      });

      it('should create an instance of InlineResponse2007', function() {
        // TODO: update the code to test InlineResponse2007
        expect(instance).to.be.a(NeuralSeek.InlineResponse2007);
      });

      it('should have the property wordCount (base name: "word_count")', function() {
        // TODO: update the code to test the property wordCount
        expect(instance).to.have.property('wordCount');
        // expect(instance.wordCount).to.be(expectedValueLiteral);
      });

      it('should have the property characterCount (base name: "character_count")', function() {
        // TODO: update the code to test the property characterCount
        expect(instance).to.have.property('characterCount');
        // expect(instance.characterCount).to.be(expectedValueLiteral);
      });

      it('should have the property detectedLanguage (base name: "detected_language")', function() {
        // TODO: update the code to test the property detectedLanguage
        expect(instance).to.have.property('detectedLanguage');
        // expect(instance.detectedLanguage).to.be(expectedValueLiteral);
      });

      it('should have the property detectedLanguageConfidence (base name: "detected_language_confidence")', function() {
        // TODO: update the code to test the property detectedLanguageConfidence
        expect(instance).to.have.property('detectedLanguageConfidence');
        // expect(instance.detectedLanguageConfidence).to.be(expectedValueLiteral);
      });

      it('should have the property translationGlossary (base name: "translation_glossary")', function() {
        // TODO: update the code to test the property translationGlossary
        expect(instance).to.have.property('translationGlossary');
        // expect(instance.translationGlossary).to.be(expectedValueLiteral);
      });

      it('should have the property translationGlossaryExact (base name: "translation_glossary_exact")', function() {
        // TODO: update the code to test the property translationGlossaryExact
        expect(instance).to.have.property('translationGlossaryExact');
        // expect(instance.translationGlossaryExact).to.be(expectedValueLiteral);
      });

      it('should have the property translations (base name: "translations")', function() {
        // TODO: update the code to test the property translations
        expect(instance).to.have.property('translations');
        // expect(instance.translations).to.be(expectedValueLiteral);
      });

    });
  });

}));
