/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NeuralSeek);
  }
}(this, function(expect, NeuralSeek) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse2002', function() {
      beforeEach(function() {
        instance = new NeuralSeek.InlineResponse2002();
      });

      it('should create an instance of InlineResponse2002', function() {
        // TODO: update the code to test InlineResponse2002
        expect(instance).to.be.a(NeuralSeek.InlineResponse2002);
      });

      it('should have the property answer (base name: "answer")', function() {
        // TODO: update the code to test the property answer
        expect(instance).to.have.property('answer');
        // expect(instance.answer).to.be(expectedValueLiteral);
      });

      it('should have the property sourceParts (base name: "sourceParts")', function() {
        // TODO: update the code to test the property sourceParts
        expect(instance).to.have.property('sourceParts');
        // expect(instance.sourceParts).to.be(expectedValueLiteral);
      });

      it('should have the property render (base name: "render")', function() {
        // TODO: update the code to test the property render
        expect(instance).to.have.property('render');
        // expect(instance.render).to.be(expectedValueLiteral);
      });

      it('should have the property variables (base name: "variables")', function() {
        // TODO: update the code to test the property variables
        expect(instance).to.have.property('variables');
        // expect(instance.variables).to.be(expectedValueLiteral);
      });

      it('should have the property variablesExpanded (base name: "variablesExpanded")', function() {
        // TODO: update the code to test the property variablesExpanded
        expect(instance).to.have.property('variablesExpanded');
        // expect(instance.variablesExpanded).to.be(expectedValueLiteral);
      });

    });
  });

}));
