/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NeuralSeek);
  }
}(this, function(expect, NeuralSeek) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse20010', function() {
      beforeEach(function() {
        instance = new NeuralSeek.InlineResponse20010();
      });

      it('should create an instance of InlineResponse20010', function() {
        // TODO: update the code to test InlineResponse20010
        expect(instance).to.be.a(NeuralSeek.InlineResponse20010);
      });

      it('should have the property pii (base name: "pii")', function() {
        // TODO: update the code to test the property pii
        expect(instance).to.have.property('pii');
        // expect(instance.pii).to.be(expectedValueLiteral);
      });

    });
  });

}));
