/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NeuralSeek);
  }
}(this, function(expect, NeuralSeek) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse2006', function() {
      beforeEach(function() {
        instance = new NeuralSeek.InlineResponse2006();
      });

      it('should create an instance of InlineResponse2006', function() {
        // TODO: update the code to test InlineResponse2006
        expect(instance).to.be.a(NeuralSeek.InlineResponse2006);
      });

      it('should have the property extractedEntities (base name: "extractedEntities")', function() {
        // TODO: update the code to test the property extractedEntities
        expect(instance).to.have.property('extractedEntities');
        // expect(instance.extractedEntities).to.be(expectedValueLiteral);
      });

      it('should have the property complete (base name: "complete")', function() {
        // TODO: update the code to test the property complete
        expect(instance).to.have.property('complete');
        // expect(instance.complete).to.be(expectedValueLiteral);
      });

      it('should have the property promptEntity (base name: "promptEntity")', function() {
        // TODO: update the code to test the property promptEntity
        expect(instance).to.have.property('promptEntity');
        // expect(instance.promptEntity).to.be(expectedValueLiteral);
      });

      it('should have the property slots (base name: "slots")', function() {
        // TODO: update the code to test the property slots
        expect(instance).to.have.property('slots');
        // expect(instance.slots).to.be(expectedValueLiteral);
      });

    });
  });

}));
