/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NeuralSeek);
  }
}(this, function(expect, NeuralSeek) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('LogExternalAgentEntries', function() {
      beforeEach(function() {
        instance = new NeuralSeek.LogExternalAgentEntries();
      });

      it('should create an instance of LogExternalAgentEntries', function() {
        // TODO: update the code to test LogExternalAgentEntries
        expect(instance).to.be.a(NeuralSeek.LogExternalAgentEntries);
      });

      it('should have the property type (base name: "type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

      it('should have the property llmtime (base name: "llmtime")', function() {
        // TODO: update the code to test the property llmtime
        expect(instance).to.have.property('llmtime');
        // expect(instance.llmtime).to.be(expectedValueLiteral);
      });

      it('should have the property inputtokencount (base name: "inputtokencount")', function() {
        // TODO: update the code to test the property inputtokencount
        expect(instance).to.have.property('inputtokencount');
        // expect(instance.inputtokencount).to.be(expectedValueLiteral);
      });

      it('should have the property generatedtokencount (base name: "generatedtokencount")', function() {
        // TODO: update the code to test the property generatedtokencount
        expect(instance).to.have.property('generatedtokencount');
        // expect(instance.generatedtokencount).to.be(expectedValueLiteral);
      });

      it('should have the property llm (base name: "llm")', function() {
        // TODO: update the code to test the property llm
        expect(instance).to.have.property('llm');
        // expect(instance.llm).to.be(expectedValueLiteral);
      });

      it('should have the property llmcode (base name: "llmcode")', function() {
        // TODO: update the code to test the property llmcode
        expect(instance).to.have.property('llmcode');
        // expect(instance.llmcode).to.be(expectedValueLiteral);
      });

      it('should have the property kbtime (base name: "kbtime")', function() {
        // TODO: update the code to test the property kbtime
        expect(instance).to.have.property('kbtime');
        // expect(instance.kbtime).to.be(expectedValueLiteral);
      });

      it('should have the property kb (base name: "kb")', function() {
        // TODO: update the code to test the property kb
        expect(instance).to.have.property('kb');
        // expect(instance.kb).to.be(expectedValueLiteral);
      });

      it('should have the property kbScore (base name: "kbScore")', function() {
        // TODO: update the code to test the property kbScore
        expect(instance).to.have.property('kbScore');
        // expect(instance.kbScore).to.be(expectedValueLiteral);
      });

      it('should have the property kbCoverage (base name: "kbCoverage")', function() {
        // TODO: update the code to test the property kbCoverage
        expect(instance).to.have.property('kbCoverage');
        // expect(instance.kbCoverage).to.be(expectedValueLiteral);
      });

      it('should have the property elementTime (base name: "elementTime")', function() {
        // TODO: update the code to test the property elementTime
        expect(instance).to.have.property('elementTime');
        // expect(instance.elementTime).to.be(expectedValueLiteral);
      });

      it('should have the property element (base name: "element")', function() {
        // TODO: update the code to test the property element
        expect(instance).to.have.property('element');
        // expect(instance.element).to.be(expectedValueLiteral);
      });

    });
  });

}));
