/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NeuralSeek);
  }
}(this, function(expect, NeuralSeek) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('LogExternalAgentBody', function() {
      beforeEach(function() {
        instance = new NeuralSeek.LogExternalAgentBody();
      });

      it('should create an instance of LogExternalAgentBody', function() {
        // TODO: update the code to test LogExternalAgentBody
        expect(instance).to.be.a(NeuralSeek.LogExternalAgentBody);
      });

      it('should have the property runId (base name: "runId")', function() {
        // TODO: update the code to test the property runId
        expect(instance).to.have.property('runId');
        // expect(instance.runId).to.be(expectedValueLiteral);
      });

      it('should have the property templateName (base name: "templateName")', function() {
        // TODO: update the code to test the property templateName
        expect(instance).to.have.property('templateName');
        // expect(instance.templateName).to.be(expectedValueLiteral);
      });

      it('should have the property user (base name: "user")', function() {
        // TODO: update the code to test the property user
        expect(instance).to.have.property('user');
        // expect(instance.user).to.be(expectedValueLiteral);
      });

      it('should have the property time (base name: "time")', function() {
        // TODO: update the code to test the property time
        expect(instance).to.have.property('time');
        // expect(instance.time).to.be(expectedValueLiteral);
      });

      it('should have the property resultsLink (base name: "resultsLink")', function() {
        // TODO: update the code to test the property resultsLink
        expect(instance).to.have.property('resultsLink');
        // expect(instance.resultsLink).to.be(expectedValueLiteral);
      });

      it('should have the property entries (base name: "entries")', function() {
        // TODO: update the code to test the property entries
        expect(instance).to.have.property('entries');
        // expect(instance.entries).to.be(expectedValueLiteral);
      });

    });
  });

}));
