/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NeuralSeek);
  }
}(this, function(expect, NeuralSeek) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('LogsBody', function() {
      beforeEach(function() {
        instance = new NeuralSeek.LogsBody();
      });

      it('should create an instance of LogsBody', function() {
        // TODO: update the code to test LogsBody
        expect(instance).to.be.a(NeuralSeek.LogsBody);
      });

      it('should have the property limit (base name: "limit")', function() {
        // TODO: update the code to test the property limit
        expect(instance).to.have.property('limit');
        // expect(instance.limit).to.be(expectedValueLiteral);
      });

      it('should have the property skip (base name: "skip")', function() {
        // TODO: update the code to test the property skip
        expect(instance).to.have.property('skip');
        // expect(instance.skip).to.be(expectedValueLiteral);
      });

      it('should have the property search (base name: "search")', function() {
        // TODO: update the code to test the property search
        expect(instance).to.have.property('search');
        // expect(instance.search).to.be(expectedValueLiteral);
      });

    });
  });

}));
