/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NeuralSeek);
  }
}(this, function(expect, NeuralSeek) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('MaistroStreamOptions', function() {
      beforeEach(function() {
        instance = new NeuralSeek.MaistroStreamOptions();
      });

      it('should create an instance of MaistroStreamOptions', function() {
        // TODO: update the code to test MaistroStreamOptions
        expect(instance).to.be.a(NeuralSeek.MaistroStreamOptions);
      });

      it('should have the property llm (base name: "llm")', function() {
        // TODO: update the code to test the property llm
        expect(instance).to.have.property('llm');
        // expect(instance.llm).to.be(expectedValueLiteral);
      });

      it('should have the property userId (base name: "user_id")', function() {
        // TODO: update the code to test the property userId
        expect(instance).to.have.property('userId');
        // expect(instance.userId).to.be(expectedValueLiteral);
      });

      it('should have the property timeout (base name: "timeout")', function() {
        // TODO: update the code to test the property timeout
        expect(instance).to.have.property('timeout');
        // expect(instance.timeout).to.be(expectedValueLiteral);
      });

      it('should have the property temperatureMod (base name: "temperatureMod")', function() {
        // TODO: update the code to test the property temperatureMod
        expect(instance).to.have.property('temperatureMod');
        // expect(instance.temperatureMod).to.be(expectedValueLiteral);
      });

      it('should have the property toppMod (base name: "toppMod")', function() {
        // TODO: update the code to test the property toppMod
        expect(instance).to.have.property('toppMod');
        // expect(instance.toppMod).to.be(expectedValueLiteral);
      });

      it('should have the property freqpenaltyMod (base name: "freqpenaltyMod")', function() {
        // TODO: update the code to test the property freqpenaltyMod
        expect(instance).to.have.property('freqpenaltyMod');
        // expect(instance.freqpenaltyMod).to.be(expectedValueLiteral);
      });

      it('should have the property minTokens (base name: "minTokens")', function() {
        // TODO: update the code to test the property minTokens
        expect(instance).to.have.property('minTokens');
        // expect(instance.minTokens).to.be(expectedValueLiteral);
      });

      it('should have the property maxTokens (base name: "maxTokens")', function() {
        // TODO: update the code to test the property maxTokens
        expect(instance).to.have.property('maxTokens');
        // expect(instance.maxTokens).to.be(expectedValueLiteral);
      });

      it('should have the property lastTurn (base name: "lastTurn")', function() {
        // TODO: update the code to test the property lastTurn
        expect(instance).to.have.property('lastTurn');
        // expect(instance.lastTurn).to.be(expectedValueLiteral);
      });

      it('should have the property returnVariables (base name: "returnVariables")', function() {
        // TODO: update the code to test the property returnVariables
        expect(instance).to.have.property('returnVariables');
        // expect(instance.returnVariables).to.be(expectedValueLiteral);
      });

      it('should have the property returnVariablesExpanded (base name: "returnVariablesExpanded")', function() {
        // TODO: update the code to test the property returnVariablesExpanded
        expect(instance).to.have.property('returnVariablesExpanded');
        // expect(instance.returnVariablesExpanded).to.be(expectedValueLiteral);
      });

      it('should have the property returnRender (base name: "returnRender")', function() {
        // TODO: update the code to test the property returnRender
        expect(instance).to.have.property('returnRender');
        // expect(instance.returnRender).to.be(expectedValueLiteral);
      });

      it('should have the property returnSource (base name: "returnSource")', function() {
        // TODO: update the code to test the property returnSource
        expect(instance).to.have.property('returnSource');
        // expect(instance.returnSource).to.be(expectedValueLiteral);
      });

      it('should have the property maxRecursion (base name: "maxRecursion")', function() {
        // TODO: update the code to test the property maxRecursion
        expect(instance).to.have.property('maxRecursion');
        // expect(instance.maxRecursion).to.be(expectedValueLiteral);
      });

    });
  });

}));
