/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NeuralSeek);
  }
}(this, function(expect, NeuralSeek) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('RateBody', function() {
      beforeEach(function() {
        instance = new NeuralSeek.RateBody();
      });

      it('should create an instance of RateBody', function() {
        // TODO: update the code to test RateBody
        expect(instance).to.be.a(NeuralSeek.RateBody);
      });

      it('should have the property answerId (base name: "answerId")', function() {
        // TODO: update the code to test the property answerId
        expect(instance).to.have.property('answerId');
        // expect(instance.answerId).to.be(expectedValueLiteral);
      });

      it('should have the property score (base name: "score")', function() {
        // TODO: update the code to test the property score
        expect(instance).to.have.property('score');
        // expect(instance.score).to.be(expectedValueLiteral);
      });

      it('should have the property feedback (base name: "feedback")', function() {
        // TODO: update the code to test the property feedback
        expect(instance).to.have.property('feedback');
        // expect(instance.feedback).to.be(expectedValueLiteral);
      });

    });
  });

}));
