/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NeuralSeek);
  }
}(this, function(expect, NeuralSeek) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SeekStreamOptionsPersonalize', function() {
      beforeEach(function() {
        instance = new NeuralSeek.SeekStreamOptionsPersonalize();
      });

      it('should create an instance of SeekStreamOptionsPersonalize', function() {
        // TODO: update the code to test SeekStreamOptionsPersonalize
        expect(instance).to.be.a(NeuralSeek.SeekStreamOptionsPersonalize);
      });

      it('should have the property preferredName (base name: "preferredName")', function() {
        // TODO: update the code to test the property preferredName
        expect(instance).to.have.property('preferredName');
        // expect(instance.preferredName).to.be(expectedValueLiteral);
      });

      it('should have the property noWelcome (base name: "noWelcome")', function() {
        // TODO: update the code to test the property noWelcome
        expect(instance).to.have.property('noWelcome');
        // expect(instance.noWelcome).to.be(expectedValueLiteral);
      });

      it('should have the property forceFirstPerson (base name: "forceFirstPerson")', function() {
        // TODO: update the code to test the property forceFirstPerson
        expect(instance).to.have.property('forceFirstPerson');
        // expect(instance.forceFirstPerson).to.be(expectedValueLiteral);
      });

      it('should have the property products (base name: "products")', function() {
        // TODO: update the code to test the property products
        expect(instance).to.have.property('products');
        // expect(instance.products).to.be(expectedValueLiteral);
      });

      it('should have the property additionalDetails (base name: "additionalDetails")', function() {
        // TODO: update the code to test the property additionalDetails
        expect(instance).to.have.property('additionalDetails');
        // expect(instance.additionalDetails).to.be(expectedValueLiteral);
      });

    });
  });

}));
