/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NeuralSeek);
  }
}(this, function(expect, NeuralSeek) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SeekStreamOptions', function() {
      beforeEach(function() {
        instance = new NeuralSeek.SeekStreamOptions();
      });

      it('should create an instance of SeekStreamOptions', function() {
        // TODO: update the code to test SeekStreamOptions
        expect(instance).to.be.a(NeuralSeek.SeekStreamOptions);
      });

      it('should have the property personalize (base name: "personalize")', function() {
        // TODO: update the code to test the property personalize
        expect(instance).to.have.property('personalize');
        // expect(instance.personalize).to.be(expectedValueLiteral);
      });

      it('should have the property proposalID (base name: "proposalID")', function() {
        // TODO: update the code to test the property proposalID
        expect(instance).to.have.property('proposalID');
        // expect(instance.proposalID).to.be(expectedValueLiteral);
      });

      it('should have the property seekLLM (base name: "seekLLM")', function() {
        // TODO: update the code to test the property seekLLM
        expect(instance).to.have.property('seekLLM');
        // expect(instance.seekLLM).to.be(expectedValueLiteral);
      });

      it('should have the property language (base name: "language")', function() {
        // TODO: update the code to test the property language
        expect(instance).to.have.property('language');
        // expect(instance.language).to.be(expectedValueLiteral);
      });

      it('should have the property filter (base name: "filter")', function() {
        // TODO: update the code to test the property filter
        expect(instance).to.have.property('filter');
        // expect(instance.filter).to.be(expectedValueLiteral);
      });

      it('should have the property lastTurn (base name: "lastTurn")', function() {
        // TODO: update the code to test the property lastTurn
        expect(instance).to.have.property('lastTurn');
        // expect(instance.lastTurn).to.be(expectedValueLiteral);
      });

      it('should have the property promptEngineering (base name: "promptEngineering")', function() {
        // TODO: update the code to test the property promptEngineering
        expect(instance).to.have.property('promptEngineering');
        // expect(instance.promptEngineering).to.be(expectedValueLiteral);
      });

      it('should have the property promptEngineeringPhrase (base name: "promptEngineeringPhrase")', function() {
        // TODO: update the code to test the property promptEngineeringPhrase
        expect(instance).to.have.property('promptEngineeringPhrase');
        // expect(instance.promptEngineeringPhrase).to.be(expectedValueLiteral);
      });

      it('should have the property answerLength (base name: "answerLength")', function() {
        // TODO: update the code to test the property answerLength
        expect(instance).to.have.property('answerLength');
        // expect(instance.answerLength).to.be(expectedValueLiteral);
      });

      it('should have the property url (base name: "url")', function() {
        // TODO: update the code to test the property url
        expect(instance).to.have.property('url');
        // expect(instance.url).to.be(expectedValueLiteral);
      });

      it('should have the property stump (base name: "stump")', function() {
        // TODO: update the code to test the property stump
        expect(instance).to.have.property('stump');
        // expect(instance.stump).to.be(expectedValueLiteral);
      });

      it('should have the property includeSourceResults (base name: "includeSourceResults")', function() {
        // TODO: update the code to test the property includeSourceResults
        expect(instance).to.have.property('includeSourceResults');
        // expect(instance.includeSourceResults).to.be(expectedValueLiteral);
      });

      it('should have the property includeHighlights (base name: "includeHighlights")', function() {
        // TODO: update the code to test the property includeHighlights
        expect(instance).to.have.property('includeHighlights');
        // expect(instance.includeHighlights).to.be(expectedValueLiteral);
      });

      it('should have the property includeSourceResultsFormatted (base name: "includeSourceResultsFormatted")', function() {
        // TODO: update the code to test the property includeSourceResultsFormatted
        expect(instance).to.have.property('includeSourceResultsFormatted');
        // expect(instance.includeSourceResultsFormatted).to.be(expectedValueLiteral);
      });

      it('should have the property sourceResultsNumber (base name: "sourceResultsNumber")', function() {
        // TODO: update the code to test the property sourceResultsNumber
        expect(instance).to.have.property('sourceResultsNumber');
        // expect(instance.sourceResultsNumber).to.be(expectedValueLiteral);
      });

      it('should have the property sourceResultsSummaryLength (base name: "sourceResultsSummaryLength")', function() {
        // TODO: update the code to test the property sourceResultsSummaryLength
        expect(instance).to.have.property('sourceResultsSummaryLength');
        // expect(instance.sourceResultsSummaryLength).to.be(expectedValueLiteral);
      });

      it('should have the property returnVariables (base name: "returnVariables")', function() {
        // TODO: update the code to test the property returnVariables
        expect(instance).to.have.property('returnVariables');
        // expect(instance.returnVariables).to.be(expectedValueLiteral);
      });

      it('should have the property returnVariablesExpanded (base name: "returnVariablesExpanded")', function() {
        // TODO: update the code to test the property returnVariablesExpanded
        expect(instance).to.have.property('returnVariablesExpanded');
        // expect(instance.returnVariablesExpanded).to.be(expectedValueLiteral);
      });

    });
  });

}));
