/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NeuralSeek);
  }
}(this, function(expect, NeuralSeek) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SeekResponse', function() {
      beforeEach(function() {
        instance = new NeuralSeek.SeekResponse();
      });

      it('should create an instance of SeekResponse', function() {
        // TODO: update the code to test SeekResponse
        expect(instance).to.be.a(NeuralSeek.SeekResponse);
      });

      it('should have the property answer (base name: "answer")', function() {
        // TODO: update the code to test the property answer
        expect(instance).to.have.property('answer');
        // expect(instance.answer).to.be(expectedValueLiteral);
      });

      it('should have the property ufa (base name: "ufa")', function() {
        // TODO: update the code to test the property ufa
        expect(instance).to.have.property('ufa');
        // expect(instance.ufa).to.be(expectedValueLiteral);
      });

      it('should have the property answerId (base name: "answerId")', function() {
        // TODO: update the code to test the property answerId
        expect(instance).to.have.property('answerId');
        // expect(instance.answerId).to.be(expectedValueLiteral);
      });

      it('should have the property thumbs (base name: "thumbs")', function() {
        // TODO: update the code to test the property thumbs
        expect(instance).to.have.property('thumbs');
        // expect(instance.thumbs).to.be(expectedValueLiteral);
      });

      it('should have the property thumbsSVG (base name: "thumbsSVG")', function() {
        // TODO: update the code to test the property thumbsSVG
        expect(instance).to.have.property('thumbsSVG');
        // expect(instance.thumbsSVG).to.be(expectedValueLiteral);
      });

      it('should have the property intent (base name: "intent")', function() {
        // TODO: update the code to test the property intent
        expect(instance).to.have.property('intent');
        // expect(instance.intent).to.be(expectedValueLiteral);
      });

      it('should have the property category (base name: "category")', function() {
        // TODO: update the code to test the property category
        expect(instance).to.have.property('category');
        // expect(instance.category).to.be(expectedValueLiteral);
      });

      it('should have the property categoryName (base name: "categoryName")', function() {
        // TODO: update the code to test the property categoryName
        expect(instance).to.have.property('categoryName');
        // expect(instance.categoryName).to.be(expectedValueLiteral);
      });

      it('should have the property score (base name: "score")', function() {
        // TODO: update the code to test the property score
        expect(instance).to.have.property('score');
        // expect(instance.score).to.be(expectedValueLiteral);
      });

      it('should have the property kBscore (base name: "KBscore")', function() {
        // TODO: update the code to test the property kBscore
        expect(instance).to.have.property('kBscore');
        // expect(instance.kBscore).to.be(expectedValueLiteral);
      });

      it('should have the property semanticAnalysis (base name: "semanticAnalysis")', function() {
        // TODO: update the code to test the property semanticAnalysis
        expect(instance).to.have.property('semanticAnalysis');
        // expect(instance.semanticAnalysis).to.be(expectedValueLiteral);
      });

      it('should have the property cachedResult (base name: "cachedResult")', function() {
        // TODO: update the code to test the property cachedResult
        expect(instance).to.have.property('cachedResult');
        // expect(instance.cachedResult).to.be(expectedValueLiteral);
      });

      it('should have the property langCode (base name: "langCode")', function() {
        // TODO: update the code to test the property langCode
        expect(instance).to.have.property('langCode');
        // expect(instance.langCode).to.be(expectedValueLiteral);
      });

      it('should have the property url (base name: "url")', function() {
        // TODO: update the code to test the property url
        expect(instance).to.have.property('url');
        // expect(instance.url).to.be(expectedValueLiteral);
      });

      it('should have the property document (base name: "document")', function() {
        // TODO: update the code to test the property document
        expect(instance).to.have.property('document');
        // expect(instance.document).to.be(expectedValueLiteral);
      });

      it('should have the property time (base name: "time")', function() {
        // TODO: update the code to test the property time
        expect(instance).to.have.property('time');
        // expect(instance.time).to.be(expectedValueLiteral);
      });

      it('should have the property kbTime (base name: "kbTime")', function() {
        // TODO: update the code to test the property kbTime
        expect(instance).to.have.property('kbTime');
        // expect(instance.kbTime).to.be(expectedValueLiteral);
      });

      it('should have the property protectTime (base name: "protectTime")', function() {
        // TODO: update the code to test the property protectTime
        expect(instance).to.have.property('protectTime');
        // expect(instance.protectTime).to.be(expectedValueLiteral);
      });

      it('should have the property categorySelectionTime (base name: "categorySelectionTime")', function() {
        // TODO: update the code to test the property categorySelectionTime
        expect(instance).to.have.property('categorySelectionTime');
        // expect(instance.categorySelectionTime).to.be(expectedValueLiteral);
      });

      it('should have the property promptInjection (base name: "promptInjection")', function() {
        // TODO: update the code to test the property promptInjection
        expect(instance).to.have.property('promptInjection');
        // expect(instance.promptInjection).to.be(expectedValueLiteral);
      });

      it('should have the property sourceResultsFormatted (base name: "sourceResultsFormatted")', function() {
        // TODO: update the code to test the property sourceResultsFormatted
        expect(instance).to.have.property('sourceResultsFormatted');
        // expect(instance.sourceResultsFormatted).to.be(expectedValueLiteral);
      });

      it('should have the property passages (base name: "passages")', function() {
        // TODO: update the code to test the property passages
        expect(instance).to.have.property('passages');
        // expect(instance.passages).to.be(expectedValueLiteral);
      });

      it('should have the property kbCoverage (base name: "kbCoverage")', function() {
        // TODO: update the code to test the property kbCoverage
        expect(instance).to.have.property('kbCoverage');
        // expect(instance.kbCoverage).to.be(expectedValueLiteral);
      });

      it('should have the property sentiment (base name: "sentiment")', function() {
        // TODO: update the code to test the property sentiment
        expect(instance).to.have.property('sentiment');
        // expect(instance.sentiment).to.be(expectedValueLiteral);
      });

      it('should have the property semanticScore (base name: "semanticScore")', function() {
        // TODO: update the code to test the property semanticScore
        expect(instance).to.have.property('semanticScore');
        // expect(instance.semanticScore).to.be(expectedValueLiteral);
      });

      it('should have the property variables (base name: "variables")', function() {
        // TODO: update the code to test the property variables
        expect(instance).to.have.property('variables');
        // expect(instance.variables).to.be(expectedValueLiteral);
      });

      it('should have the property variablesExpanded (base name: "variablesExpanded")', function() {
        // TODO: update the code to test the property variablesExpanded
        expect(instance).to.have.property('variablesExpanded');
        // expect(instance.variablesExpanded).to.be(expectedValueLiteral);
      });

    });
  });

}));
