/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NeuralSeek);
  }
}(this, function(expect, NeuralSeek) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TranslateBody', function() {
      beforeEach(function() {
        instance = new NeuralSeek.TranslateBody();
      });

      it('should create an instance of TranslateBody', function() {
        // TODO: update the code to test TranslateBody
        expect(instance).to.be.a(NeuralSeek.TranslateBody);
      });

      it('should have the property text (base name: "text")', function() {
        // TODO: update the code to test the property text
        expect(instance).to.have.property('text');
        // expect(instance.text).to.be(expectedValueLiteral);
      });

      it('should have the property modelId (base name: "model_id")', function() {
        // TODO: update the code to test the property modelId
        expect(instance).to.have.property('modelId');
        // expect(instance.modelId).to.be(expectedValueLiteral);
      });

      it('should have the property target (base name: "target")', function() {
        // TODO: update the code to test the property target
        expect(instance).to.have.property('target');
        // expect(instance.target).to.be(expectedValueLiteral);
      });

      it('should have the property llmId (base name: "llmId")', function() {
        // TODO: update the code to test the property llmId
        expect(instance).to.have.property('llmId');
        // expect(instance.llmId).to.be(expectedValueLiteral);
      });

      it('should have the property maxChunk (base name: "maxChunk")', function() {
        // TODO: update the code to test the property maxChunk
        expect(instance).to.have.property('maxChunk');
        // expect(instance.maxChunk).to.be(expectedValueLiteral);
      });

      it('should have the property additionalInstructions (base name: "additionalInstructions")', function() {
        // TODO: update the code to test the property additionalInstructions
        expect(instance).to.have.property('additionalInstructions');
        // expect(instance.additionalInstructions).to.be(expectedValueLiteral);
      });

    });
  });

}));
