/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NeuralSeek);
  }
}(this, function(expect, NeuralSeek) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TranslateGlossaryBody1', function() {
      beforeEach(function() {
        instance = new NeuralSeek.TranslateGlossaryBody1();
      });

      it('should create an instance of TranslateGlossaryBody1', function() {
        // TODO: update the code to test TranslateGlossaryBody1
        expect(instance).to.be.a(NeuralSeek.TranslateGlossaryBody1);
      });

      it('should have the property sentences (base name: "sentences")', function() {
        // TODO: update the code to test the property sentences
        expect(instance).to.have.property('sentences');
        // expect(instance.sentences).to.be(expectedValueLiteral);
      });

    });
  });

}));
