/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import ChatCompletionsBody from '../model/ChatCompletionsBody';
import InlineResponse2002 from '../model/InlineResponse2002';
import InlineResponse2003 from '../model/InlineResponse2003';
import InlineResponse2004 from '../model/InlineResponse2004';
import MaistroBatchBody from '../model/MaistroBatchBody';
import MaistroBody from '../model/MaistroBody';
import MaistroStreamBody from '../model/MaistroStreamBody';

/**
* MAIstro service.
* @module MAIstroApi
* @version 1.0.1
*/
export default class MAIstroApi {

    /**
    * Constructs a new MAIstroApi. 
    * @alias module:MAIstroApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the chat operation.
     * @callback moduleMAIstroApi~chatCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2004{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Chat Completions - compatible mAIStro endpoint
     * Call a mAIstro agent using the openAI chat completions schema.
     * @param {Object} opts Optional parameters
     * @param {module:model/ChatCompletionsBody} opts.body 
     * @param {String} opts.runid Optional header to specify the run ID
     * @param {module:MAIstroApi~chatCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    chat(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        'runid': opts['runid']
      };
      let formParams = {
        
      };

      let authNames = ['apiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json', 'text/event-stream'];
      let returnType = InlineResponse2004;

      return this.apiClient.callApi(
        '/chat/completions', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the maistro operation.
     * @callback moduleMAIstroApi~maistroCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2002{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Run mAistro NTL or agent
     * Freeform prompting using NeuralSeek Template Language or a saved agent
     * @param {module:model/MaistroBody} body The request object.
     * @param {Object} opts Optional parameters
     * @param {String} opts.overrideschema Find variables based on post body.  Return all variables as the base presponse body, overriding the normal NS schema. All POST options will be ignored. Set this to a string value of &#x27;true&#x27; to activate
     * @param {String} opts.overrideagent If using overrideSchema you must pass your agent name here. All other POST options will be ignored.
     * @param {String} opts.debug Include NS debug information in a field named &#x27;neuralseek&#x27;. Set this to a string value of &#x27;true&#x27; to activate
     * @param {module:MAIstroApi~maistroCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    maistro(body, opts, callback) {
      opts = opts || {};
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling maistro");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'overrideschema': opts['overrideschema'],'overrideagent': opts['overrideagent'],'debug': opts['debug']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['apiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InlineResponse2002;

      return this.apiClient.callApi(
        '/maistro', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the maistroAgentGet operation.
     * @callback moduleMAIstroApi~maistroAgentGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2002{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Run a mAIstro agent via GET
     * Run a mAIstro agent via GET
     * @param {String} agent The saved mAIstro agent to run
     * @param {Object} opts Optional parameters
     * @param {String} opts.params Pass your mAIstro params as query parameters in simple name&#x3D;value format
     * @param {module:MAIstroApi~maistroAgentGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    maistroAgentGet(agent, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'agent' is set
      if (agent === undefined || agent === null) {
        throw new Error("Missing the required parameter 'agent' when calling maistroAgentGet");
      }

      let pathParams = {
        'agent': agent
      };
      let queryParams = {
        'params': opts['params']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['apiKey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2002;

      return this.apiClient.callApi(
        '/maistro/{agent}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the maistroBatch operation.
     * @callback moduleMAIstroApi~maistroBatchCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Call mAIstro NTL or an agent via batch
     * Freeform prompting using NeuralSeek Template Language or a saved agent run in batch mode
     * @param {module:model/MaistroBatchBody} body The request object.
     * @param {module:MAIstroApi~maistroBatchCallback} callback The callback function, accepting three arguments: error, data, response
     */
    maistroBatch(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling maistroBatch");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['apiKey'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/maistro_batch', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the maistroBatchDelete operation.
     * @callback moduleMAIstroApi~maistroBatchDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Cancel current mAIstro batch run
     * Cancel current mAIstro batch run
     * @param {module:MAIstroApi~maistroBatchDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    maistroBatchDelete(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['apiKey'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/maistro_batch', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the maistroBatchGet operation.
     * @callback moduleMAIstroApi~maistroBatchGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2002{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get mAIstro batch results
     * Retrieve results from a mAIstro batch run
     * @param {module:MAIstroApi~maistroBatchGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    maistroBatchGet(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['apiKey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2002;

      return this.apiClient.callApi(
        '/maistro_batch', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the maistroStream operation.
     * @callback moduleMAIstroApi~maistroStreamCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2003{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Stream mAIstro NTL or an agent
     * Freeform prompting using NeuralSeek Template Language or a saved agent
     * @param {module:model/MaistroStreamBody} body The request object.
     * @param {module:MAIstroApi~maistroStreamCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    maistroStream(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling maistroStream");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['apiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['text/event-stream'];
      let returnType = InlineResponse2003;

      return this.apiClient.callApi(
        '/maistro_stream', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}