/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import TestBody1 from '../model/TestBody1';

/**
* TestQuestions service.
* @module TestQuestionsApi
* @version 1.0.1
*/
export default class TestQuestionsApi {

    /**
    * Constructs a new TestQuestionsApi. 
    * @alias module:TestQuestionsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the getTestResults operation.
     * @callback moduleTestQuestionsApi~getTestResultsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Test Results
     * Retrieve an results from the test endpoint
     * @param {module:TestQuestionsApi~getTestResultsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getTestResults(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['apiKey'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/getTestResults', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the test operation.
     * @callback moduleTestQuestionsApi~testCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Test questions via batch upload
     * Test questions via batch upload
     * @param {Object} opts Optional parameters
     * @param {Blob} opts.file 
     * @param {module:model/TestBody1} opts.body The questions csv.  Must adhere to the template https://api.neuralseek.com/q.csv After upload you will receive a 202 response and the server will begin processing.  Check for your completed results on the getTestResults endpoint.
     * @param {module:TestQuestionsApi~testCallback} callback The callback function, accepting three arguments: error, data, response
     */
    test(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        'file': opts['file']
      };

      let authNames = ['apiKey'];
      let contentTypes = ['multipart/form-data', 'application/json'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/test', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}