/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NeuralSeek);
  }
}(this, function(expect, NeuralSeek) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NeuralSeek.MAIstroApi();
  });

  describe('(package)', function() {
    describe('MAIstroApi', function() {
      describe('chat', function() {
        it('should call chat successfully', function(done) {
          // TODO: uncomment, update parameter values for chat call and complete the assertions
          /*
          var opts = {};

          instance.chat(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NeuralSeek.InlineResponse2004);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('maistro', function() {
        it('should call maistro successfully', function(done) {
          // TODO: uncomment, update parameter values for maistro call and complete the assertions
          /*
          var opts = {};

          instance.maistro(body, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NeuralSeek.InlineResponse2002);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('maistroAgentGet', function() {
        it('should call maistroAgentGet successfully', function(done) {
          // TODO: uncomment, update parameter values for maistroAgentGet call and complete the assertions
          /*
          var opts = {};

          instance.maistroAgentGet(agent, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NeuralSeek.InlineResponse2002);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('maistroBatch', function() {
        it('should call maistroBatch successfully', function(done) {
          // TODO: uncomment, update parameter values for maistroBatch call
          /*

          instance.maistroBatch(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('maistroBatchDelete', function() {
        it('should call maistroBatchDelete successfully', function(done) {
          // TODO: uncomment maistroBatchDelete call
          /*

          instance.maistroBatchDelete(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('maistroBatchGet', function() {
        it('should call maistroBatchGet successfully', function(done) {
          // TODO: uncomment maistroBatchGet call and complete the assertions
          /*

          instance.maistroBatchGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NeuralSeek.InlineResponse2002);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('maistroStream', function() {
        it('should call maistroStream successfully', function(done) {
          // TODO: uncomment, update parameter values for maistroStream call and complete the assertions
          /*

          instance.maistroStream(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NeuralSeek.InlineResponse2003);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
