/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NeuralSeek);
  }
}(this, function(expect, NeuralSeek) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NeuralSeek.MAIstroAgentRatingsApi();
  });

  describe('(package)', function() {
    describe('MAIstroAgentRatingsApi', function() {
      describe('maistroRate', function() {
        it('should call maistroRate successfully', function(done) {
          // TODO: uncomment, update parameter values for maistroRate call
          /*

          instance.maistroRate(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('maistroRatings', function() {
        it('should call maistroRatings successfully', function(done) {
          // TODO: uncomment, update parameter values for maistroRatings call and complete the assertions
          /*

          instance.maistroRatings(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NeuralSeek.InlineResponse2001);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
