/*
 * NeuralSeek
 * NeuralSeek - The business LLM accelerator
 *
 * OpenAPI spec version: 1.0.1
 * Contact: support@NeuralSeek.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NeuralSeek);
  }
}(this, function(expect, NeuralSeek) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NeuralSeek.TranslateApi();
  });

  describe('(package)', function() {
    describe('TranslateApi', function() {
      describe('deleteTranslateGlossary', function() {
        it('should call deleteTranslateGlossary successfully', function(done) {
          // TODO: uncomment deleteTranslateGlossary call
          /*

          instance.deleteTranslateGlossary(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('identifyLanguage', function() {
        it('should call identifyLanguage successfully', function(done) {
          // TODO: uncomment, update parameter values for identifyLanguage call and complete the assertions
          /*

          instance.identifyLanguage(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(NeuralSeek.InlineResponse2008);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('identifyLanguageJSON', function() {
        it('should call identifyLanguageJSON successfully', function(done) {
          // TODO: uncomment, update parameter values for identifyLanguageJSON call and complete the assertions
          /*

          instance.identifyLanguageJSON(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NeuralSeek.InlineResponse2009);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('translate', function() {
        it('should call translate successfully', function(done) {
          // TODO: uncomment, update parameter values for translate call and complete the assertions
          /*

          instance.translate(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(NeuralSeek.InlineResponse2007);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('translateGlossary', function() {
        it('should call translateGlossary successfully', function(done) {
          // TODO: uncomment, update parameter values for translateGlossary call
          /*

          instance.translateGlossary(file, body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
